// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: igpsport/ble.proto

package nodomain.freeyourgadget.gadgetbridge.proto.igpsport;

public final class Ble {
  private Ble() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code BLE_OPERATE_TYPE}
   */
  public enum BLE_OPERATE_TYPE
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>enum_BLE_OPERATE_TYPE_NONE = 0;</code>
     */
    enum_BLE_OPERATE_TYPE_NONE(0),
    /**
     * <code>enum_BLE_OPERATE_TYPE_BOND_INFO = 1;</code>
     */
    enum_BLE_OPERATE_TYPE_BOND_INFO(1),
    /**
     * <code>enum_BLE_OPERATE_TYPE_BOND_REQ = 2;</code>
     */
    enum_BLE_OPERATE_TYPE_BOND_REQ(2),
    /**
     * <code>enum_BLE_OPERATE_TYPE_CONNECT_STATUS = 3;</code>
     */
    enum_BLE_OPERATE_TYPE_CONNECT_STATUS(3),
    /**
     * <code>enum_BLE_OPERATE_TYPE_UNBOND = 4;</code>
     */
    enum_BLE_OPERATE_TYPE_UNBOND(4),
    ;

    /**
     * <code>enum_BLE_OPERATE_TYPE_NONE = 0;</code>
     */
    public static final int enum_BLE_OPERATE_TYPE_NONE_VALUE = 0;
    /**
     * <code>enum_BLE_OPERATE_TYPE_BOND_INFO = 1;</code>
     */
    public static final int enum_BLE_OPERATE_TYPE_BOND_INFO_VALUE = 1;
    /**
     * <code>enum_BLE_OPERATE_TYPE_BOND_REQ = 2;</code>
     */
    public static final int enum_BLE_OPERATE_TYPE_BOND_REQ_VALUE = 2;
    /**
     * <code>enum_BLE_OPERATE_TYPE_CONNECT_STATUS = 3;</code>
     */
    public static final int enum_BLE_OPERATE_TYPE_CONNECT_STATUS_VALUE = 3;
    /**
     * <code>enum_BLE_OPERATE_TYPE_UNBOND = 4;</code>
     */
    public static final int enum_BLE_OPERATE_TYPE_UNBOND_VALUE = 4;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BLE_OPERATE_TYPE valueOf(int value) {
      return forNumber(value);
    }

    public static BLE_OPERATE_TYPE forNumber(int value) {
      switch (value) {
        case 0: return enum_BLE_OPERATE_TYPE_NONE;
        case 1: return enum_BLE_OPERATE_TYPE_BOND_INFO;
        case 2: return enum_BLE_OPERATE_TYPE_BOND_REQ;
        case 3: return enum_BLE_OPERATE_TYPE_CONNECT_STATUS;
        case 4: return enum_BLE_OPERATE_TYPE_UNBOND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BLE_OPERATE_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BLE_OPERATE_TYPE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BLE_OPERATE_TYPE>() {
            @java.lang.Override
            public BLE_OPERATE_TYPE findValueByNumber(int number) {
              return BLE_OPERATE_TYPE.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return BLE_OPERATE_TYPEVerifier.INSTANCE;
    }

    private static final class BLE_OPERATE_TYPEVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new BLE_OPERATE_TYPEVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return BLE_OPERATE_TYPE.forNumber(number) != null;
            }
          };

    private final int value;

    private BLE_OPERATE_TYPE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BLE_OPERATE_TYPE)
  }

  public interface ble_data_messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ble_data_message)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 status = 1;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>optional uint32 status = 1;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>optional string member_id = 2;</code>
     * @return Whether the memberId field is set.
     */
    boolean hasMemberId();
    /**
     * <code>optional string member_id = 2;</code>
     * @return The memberId.
     */
    java.lang.String getMemberId();
    /**
     * <code>optional string member_id = 2;</code>
     * @return The bytes for memberId.
     */
    com.google.protobuf.ByteString
        getMemberIdBytes();
  }
  /**
   * Protobuf type {@code ble_data_message}
   */
  public  static final class ble_data_message extends
      com.google.protobuf.GeneratedMessageLite<
          ble_data_message, ble_data_message.Builder> implements
      // @@protoc_insertion_point(message_implements:ble_data_message)
      ble_data_messageOrBuilder {
    private ble_data_message() {
      memberId_ = "";
    }
    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>optional uint32 status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>optional uint32 status = 1;</code>
     * @param value The status to set.
     */
    private void setStatus(int value) {
      bitField0_ |= 0x00000001;
      status_ = value;
    }
    /**
     * <code>optional uint32 status = 1;</code>
     */
    private void clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
    }

    public static final int MEMBER_ID_FIELD_NUMBER = 2;
    private java.lang.String memberId_;
    /**
     * <code>optional string member_id = 2;</code>
     * @return Whether the memberId field is set.
     */
    @java.lang.Override
    public boolean hasMemberId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string member_id = 2;</code>
     * @return The memberId.
     */
    @java.lang.Override
    public java.lang.String getMemberId() {
      return memberId_;
    }
    /**
     * <code>optional string member_id = 2;</code>
     * @return The bytes for memberId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMemberIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(memberId_);
    }
    /**
     * <code>optional string member_id = 2;</code>
     * @param value The memberId to set.
     */
    private void setMemberId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      memberId_ = value;
    }
    /**
     * <code>optional string member_id = 2;</code>
     */
    private void clearMemberId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      memberId_ = getDefaultInstance().getMemberId();
    }
    /**
     * <code>optional string member_id = 2;</code>
     * @param value The bytes for memberId to set.
     */
    private void setMemberIdBytes(
        com.google.protobuf.ByteString value) {
      memberId_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ble_data_message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message, Builder> implements
        // @@protoc_insertion_point(builder_implements:ble_data_message)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_messageOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 status = 1;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override
      public boolean hasStatus() {
        return instance.hasStatus();
      }
      /**
       * <code>optional uint32 status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>optional uint32 status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>optional uint32 status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>optional string member_id = 2;</code>
       * @return Whether the memberId field is set.
       */
      @java.lang.Override
      public boolean hasMemberId() {
        return instance.hasMemberId();
      }
      /**
       * <code>optional string member_id = 2;</code>
       * @return The memberId.
       */
      @java.lang.Override
      public java.lang.String getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>optional string member_id = 2;</code>
       * @return The bytes for memberId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMemberIdBytes() {
        return instance.getMemberIdBytes();
      }
      /**
       * <code>optional string member_id = 2;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(
          java.lang.String value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>optional string member_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }
      /**
       * <code>optional string member_id = 2;</code>
       * @param value The bytes for memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMemberIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ble_data_message)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "status_",
              "memberId_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u100b\u0000\u0002" +
                "\u1008\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ble_data_message)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message DEFAULT_INSTANCE;
    static {
      ble_data_message defaultInstance = new ble_data_message();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ble_data_message.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ble_data_message> PARSER;

    public static com.google.protobuf.Parser<ble_data_message> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ble_msgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ble_msg)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
     * @return Whether the serviceType field is set.
     */
    boolean hasServiceType();
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
     * @return The serviceType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index getServiceType();

    /**
     * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
     * @return Whether the bleOperateType field is set.
     */
    boolean hasBleOperateType();
    /**
     * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
     * @return The bleOperateType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.BLE_OPERATE_TYPE getBleOperateType();

    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    java.util.List<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message> 
        getBleDataMsgList();
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message getBleDataMsg(int index);
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    int getBleDataMsgCount();
  }
  /**
   * Protobuf type {@code ble_msg}
   */
  public  static final class ble_msg extends
      com.google.protobuf.GeneratedMessageLite<
          ble_msg, ble_msg.Builder> implements
      // @@protoc_insertion_point(message_implements:ble_msg)
      ble_msgOrBuilder {
    private ble_msg() {
      serviceType_ = 10;
      bleDataMsg_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int SERVICE_TYPE_FIELD_NUMBER = 1;
    private int serviceType_;
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
     * @return Whether the serviceType field is set.
     */
    @java.lang.Override
    public boolean hasServiceType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
     * @return The serviceType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index getServiceType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index.forNumber(serviceType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index.enum_SERVICE_TYPE_INDEX_BLE : result;
    }
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
     * @param value The serviceType to set.
     */
    private void setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index value) {
      serviceType_ = value.getNumber();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
     */
    private void clearServiceType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      serviceType_ = 10;
    }

    public static final int BLE_OPERATE_TYPE_FIELD_NUMBER = 2;
    private int bleOperateType_;
    /**
     * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
     * @return Whether the bleOperateType field is set.
     */
    @java.lang.Override
    public boolean hasBleOperateType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
     * @return The bleOperateType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.BLE_OPERATE_TYPE getBleOperateType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.BLE_OPERATE_TYPE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.BLE_OPERATE_TYPE.forNumber(bleOperateType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.BLE_OPERATE_TYPE.enum_BLE_OPERATE_TYPE_NONE : result;
    }
    /**
     * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
     * @param value The bleOperateType to set.
     */
    private void setBleOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.BLE_OPERATE_TYPE value) {
      bleOperateType_ = value.getNumber();
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
     */
    private void clearBleOperateType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bleOperateType_ = 0;
    }

    public static final int BLE_DATA_MSG_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message> bleDataMsg_;
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    @java.lang.Override
    public java.util.List<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message> getBleDataMsgList() {
      return bleDataMsg_;
    }
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    public java.util.List<? extends nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_messageOrBuilder> 
        getBleDataMsgOrBuilderList() {
      return bleDataMsg_;
    }
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    @java.lang.Override
    public int getBleDataMsgCount() {
      return bleDataMsg_.size();
    }
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message getBleDataMsg(int index) {
      return bleDataMsg_.get(index);
    }
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_messageOrBuilder getBleDataMsgOrBuilder(
        int index) {
      return bleDataMsg_.get(index);
    }
    private void ensureBleDataMsgIsMutable() {
      com.google.protobuf.Internal.ProtobufList<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message> tmp = bleDataMsg_;
      if (!tmp.isModifiable()) {
        bleDataMsg_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    private void setBleDataMsg(
        int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message value) {
      value.getClass();
  ensureBleDataMsgIsMutable();
      bleDataMsg_.set(index, value);
    }
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    private void addBleDataMsg(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message value) {
      value.getClass();
  ensureBleDataMsgIsMutable();
      bleDataMsg_.add(value);
    }
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    private void addBleDataMsg(
        int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message value) {
      value.getClass();
  ensureBleDataMsgIsMutable();
      bleDataMsg_.add(index, value);
    }
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    private void addAllBleDataMsg(
        java.lang.Iterable<? extends nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message> values) {
      ensureBleDataMsgIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, bleDataMsg_);
    }
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    private void clearBleDataMsg() {
      bleDataMsg_ = emptyProtobufList();
    }
    /**
     * <code>repeated .ble_data_message ble_data_msg = 3;</code>
     */
    private void removeBleDataMsg(int index) {
      ensureBleDataMsgIsMutable();
      bleDataMsg_.remove(index);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ble_msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg, Builder> implements
        // @@protoc_insertion_point(builder_implements:ble_msg)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msgOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
       * @return Whether the serviceType field is set.
       */
      @java.lang.Override
      public boolean hasServiceType() {
        return instance.hasServiceType();
      }
      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
       * @return The serviceType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index getServiceType() {
        return instance.getServiceType();
      }
      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
       * @param value The enum numeric value on the wire for serviceType to set.
       * @return This builder for chaining.
       */
      public Builder setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index value) {
        copyOnWrite();
        instance.setServiceType(value);
        return this;
      }
      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_BLE];</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceType() {
        copyOnWrite();
        instance.clearServiceType();
        return this;
      }

      /**
       * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
       * @return Whether the bleOperateType field is set.
       */
      @java.lang.Override
      public boolean hasBleOperateType() {
        return instance.hasBleOperateType();
      }
      /**
       * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
       * @return The bleOperateType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.BLE_OPERATE_TYPE getBleOperateType() {
        return instance.getBleOperateType();
      }
      /**
       * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
       * @param value The enum numeric value on the wire for bleOperateType to set.
       * @return This builder for chaining.
       */
      public Builder setBleOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.BLE_OPERATE_TYPE value) {
        copyOnWrite();
        instance.setBleOperateType(value);
        return this;
      }
      /**
       * <code>required .BLE_OPERATE_TYPE ble_operate_type = 2 [default = enum_BLE_OPERATE_TYPE_NONE];</code>
       * @return This builder for chaining.
       */
      public Builder clearBleOperateType() {
        copyOnWrite();
        instance.clearBleOperateType();
        return this;
      }

      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      @java.lang.Override
      public java.util.List<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message> getBleDataMsgList() {
        return java.util.Collections.unmodifiableList(
            instance.getBleDataMsgList());
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      @java.lang.Override
      public int getBleDataMsgCount() {
        return instance.getBleDataMsgCount();
      }/**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message getBleDataMsg(int index) {
        return instance.getBleDataMsg(index);
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      public Builder setBleDataMsg(
          int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message value) {
        copyOnWrite();
        instance.setBleDataMsg(index, value);
        return this;
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      public Builder setBleDataMsg(
          int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message.Builder builderForValue) {
        copyOnWrite();
        instance.setBleDataMsg(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      public Builder addBleDataMsg(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message value) {
        copyOnWrite();
        instance.addBleDataMsg(value);
        return this;
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      public Builder addBleDataMsg(
          int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message value) {
        copyOnWrite();
        instance.addBleDataMsg(index, value);
        return this;
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      public Builder addBleDataMsg(
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message.Builder builderForValue) {
        copyOnWrite();
        instance.addBleDataMsg(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      public Builder addBleDataMsg(
          int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message.Builder builderForValue) {
        copyOnWrite();
        instance.addBleDataMsg(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      public Builder addAllBleDataMsg(
          java.lang.Iterable<? extends nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message> values) {
        copyOnWrite();
        instance.addAllBleDataMsg(values);
        return this;
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      public Builder clearBleDataMsg() {
        copyOnWrite();
        instance.clearBleDataMsg();
        return this;
      }
      /**
       * <code>repeated .ble_data_message ble_data_msg = 3;</code>
       */
      public Builder removeBleDataMsg(int index) {
        copyOnWrite();
        instance.removeBleDataMsg(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ble_msg)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "serviceType_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index.internalGetVerifier(),
              "bleOperateType_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.BLE_OPERATE_TYPE.internalGetVerifier(),
              "bleDataMsg_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_data_message.class,
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0001\u0002\u0001\u150c\u0000\u0002" +
                "\u150c\u0001\u0003\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ble_msg)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg DEFAULT_INSTANCE;
    static {
      ble_msg defaultInstance = new ble_msg();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ble_msg.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Ble.ble_msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ble_msg> PARSER;

    public static com.google.protobuf.Parser<ble_msg> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
