// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: igpsport/file_download.proto

package nodomain.freeyourgadget.gadgetbridge.proto.igpsport;

public final class FileDownload {
  private FileDownload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface file_downloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:file_download)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 file_size = 1;</code>
     * @return Whether the fileSize field is set.
     */
    boolean hasFileSize();
    /**
     * <code>required uint32 file_size = 1;</code>
     * @return The fileSize.
     */
    int getFileSize();

    /**
     * <code>optional uint32 file_type = 2;</code>
     * @return Whether the fileType field is set.
     */
    boolean hasFileType();
    /**
     * <code>optional uint32 file_type = 2;</code>
     * @return The fileType.
     */
    int getFileType();

    /**
     * <code>optional uint32 file_id = 3;</code>
     * @return Whether the fileId field is set.
     */
    boolean hasFileId();
    /**
     * <code>optional uint32 file_id = 3;</code>
     * @return The fileId.
     */
    int getFileId();

    /**
     * <code>optional string file_name = 4;</code>
     * @return Whether the fileName field is set.
     */
    boolean hasFileName();
    /**
     * <code>optional string file_name = 4;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>optional string file_name = 4;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional uint32 file_verify_val = 7;</code>
     * @return Whether the fileVerifyVal field is set.
     */
    boolean hasFileVerifyVal();
    /**
     * <code>optional uint32 file_verify_val = 7;</code>
     * @return The fileVerifyVal.
     */
    int getFileVerifyVal();

    /**
     * <code>optional uint32 file_crc32 = 8;</code>
     * @return Whether the fileCrc32 field is set.
     */
    boolean hasFileCrc32();
    /**
     * <code>optional uint32 file_crc32 = 8;</code>
     * @return The fileCrc32.
     */
    int getFileCrc32();
  }
  /**
   * Protobuf type {@code file_download}
   */
  public  static final class file_download extends
      com.google.protobuf.GeneratedMessageLite<
          file_download, file_download.Builder> implements
      // @@protoc_insertion_point(message_implements:file_download)
      file_downloadOrBuilder {
    private file_download() {
      fileName_ = "";
    }
    private int bitField0_;
    public static final int FILE_SIZE_FIELD_NUMBER = 1;
    private int fileSize_;
    /**
     * <code>required uint32 file_size = 1;</code>
     * @return Whether the fileSize field is set.
     */
    @java.lang.Override
    public boolean hasFileSize() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required uint32 file_size = 1;</code>
     * @return The fileSize.
     */
    @java.lang.Override
    public int getFileSize() {
      return fileSize_;
    }
    /**
     * <code>required uint32 file_size = 1;</code>
     * @param value The fileSize to set.
     */
    private void setFileSize(int value) {
      bitField0_ |= 0x00000001;
      fileSize_ = value;
    }
    /**
     * <code>required uint32 file_size = 1;</code>
     */
    private void clearFileSize() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fileSize_ = 0;
    }

    public static final int FILE_TYPE_FIELD_NUMBER = 2;
    private int fileType_;
    /**
     * <code>optional uint32 file_type = 2;</code>
     * @return Whether the fileType field is set.
     */
    @java.lang.Override
    public boolean hasFileType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 file_type = 2;</code>
     * @return The fileType.
     */
    @java.lang.Override
    public int getFileType() {
      return fileType_;
    }
    /**
     * <code>optional uint32 file_type = 2;</code>
     * @param value The fileType to set.
     */
    private void setFileType(int value) {
      bitField0_ |= 0x00000002;
      fileType_ = value;
    }
    /**
     * <code>optional uint32 file_type = 2;</code>
     */
    private void clearFileType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      fileType_ = 0;
    }

    public static final int FILE_ID_FIELD_NUMBER = 3;
    private int fileId_;
    /**
     * <code>optional uint32 file_id = 3;</code>
     * @return Whether the fileId field is set.
     */
    @java.lang.Override
    public boolean hasFileId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 file_id = 3;</code>
     * @return The fileId.
     */
    @java.lang.Override
    public int getFileId() {
      return fileId_;
    }
    /**
     * <code>optional uint32 file_id = 3;</code>
     * @param value The fileId to set.
     */
    private void setFileId(int value) {
      bitField0_ |= 0x00000004;
      fileId_ = value;
    }
    /**
     * <code>optional uint32 file_id = 3;</code>
     */
    private void clearFileId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      fileId_ = 0;
    }

    public static final int FILE_NAME_FIELD_NUMBER = 4;
    private java.lang.String fileName_;
    /**
     * <code>optional string file_name = 4;</code>
     * @return Whether the fileName field is set.
     */
    @java.lang.Override
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string file_name = 4;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      return fileName_;
    }
    /**
     * <code>optional string file_name = 4;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fileName_);
    }
    /**
     * <code>optional string file_name = 4;</code>
     * @param value The fileName to set.
     */
    private void setFileName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000008;
      fileName_ = value;
    }
    /**
     * <code>optional string file_name = 4;</code>
     */
    private void clearFileName() {
      bitField0_ = (bitField0_ & ~0x00000008);
      fileName_ = getDefaultInstance().getFileName();
    }
    /**
     * <code>optional string file_name = 4;</code>
     * @param value The bytes for fileName to set.
     */
    private void setFileNameBytes(
        com.google.protobuf.ByteString value) {
      fileName_ = value.toStringUtf8();
      bitField0_ |= 0x00000008;
    }

    public static final int FILE_VERIFY_VAL_FIELD_NUMBER = 7;
    private int fileVerifyVal_;
    /**
     * <code>optional uint32 file_verify_val = 7;</code>
     * @return Whether the fileVerifyVal field is set.
     */
    @java.lang.Override
    public boolean hasFileVerifyVal() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 file_verify_val = 7;</code>
     * @return The fileVerifyVal.
     */
    @java.lang.Override
    public int getFileVerifyVal() {
      return fileVerifyVal_;
    }
    /**
     * <code>optional uint32 file_verify_val = 7;</code>
     * @param value The fileVerifyVal to set.
     */
    private void setFileVerifyVal(int value) {
      bitField0_ |= 0x00000010;
      fileVerifyVal_ = value;
    }
    /**
     * <code>optional uint32 file_verify_val = 7;</code>
     */
    private void clearFileVerifyVal() {
      bitField0_ = (bitField0_ & ~0x00000010);
      fileVerifyVal_ = 0;
    }

    public static final int FILE_CRC32_FIELD_NUMBER = 8;
    private int fileCrc32_;
    /**
     * <code>optional uint32 file_crc32 = 8;</code>
     * @return Whether the fileCrc32 field is set.
     */
    @java.lang.Override
    public boolean hasFileCrc32() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 file_crc32 = 8;</code>
     * @return The fileCrc32.
     */
    @java.lang.Override
    public int getFileCrc32() {
      return fileCrc32_;
    }
    /**
     * <code>optional uint32 file_crc32 = 8;</code>
     * @param value The fileCrc32 to set.
     */
    private void setFileCrc32(int value) {
      bitField0_ |= 0x00000020;
      fileCrc32_ = value;
    }
    /**
     * <code>optional uint32 file_crc32 = 8;</code>
     */
    private void clearFileCrc32() {
      bitField0_ = (bitField0_ & ~0x00000020);
      fileCrc32_ = 0;
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code file_download}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download, Builder> implements
        // @@protoc_insertion_point(builder_implements:file_download)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_downloadOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required uint32 file_size = 1;</code>
       * @return Whether the fileSize field is set.
       */
      @java.lang.Override
      public boolean hasFileSize() {
        return instance.hasFileSize();
      }
      /**
       * <code>required uint32 file_size = 1;</code>
       * @return The fileSize.
       */
      @java.lang.Override
      public int getFileSize() {
        return instance.getFileSize();
      }
      /**
       * <code>required uint32 file_size = 1;</code>
       * @param value The fileSize to set.
       * @return This builder for chaining.
       */
      public Builder setFileSize(int value) {
        copyOnWrite();
        instance.setFileSize(value);
        return this;
      }
      /**
       * <code>required uint32 file_size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSize() {
        copyOnWrite();
        instance.clearFileSize();
        return this;
      }

      /**
       * <code>optional uint32 file_type = 2;</code>
       * @return Whether the fileType field is set.
       */
      @java.lang.Override
      public boolean hasFileType() {
        return instance.hasFileType();
      }
      /**
       * <code>optional uint32 file_type = 2;</code>
       * @return The fileType.
       */
      @java.lang.Override
      public int getFileType() {
        return instance.getFileType();
      }
      /**
       * <code>optional uint32 file_type = 2;</code>
       * @param value The fileType to set.
       * @return This builder for chaining.
       */
      public Builder setFileType(int value) {
        copyOnWrite();
        instance.setFileType(value);
        return this;
      }
      /**
       * <code>optional uint32 file_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileType() {
        copyOnWrite();
        instance.clearFileType();
        return this;
      }

      /**
       * <code>optional uint32 file_id = 3;</code>
       * @return Whether the fileId field is set.
       */
      @java.lang.Override
      public boolean hasFileId() {
        return instance.hasFileId();
      }
      /**
       * <code>optional uint32 file_id = 3;</code>
       * @return The fileId.
       */
      @java.lang.Override
      public int getFileId() {
        return instance.getFileId();
      }
      /**
       * <code>optional uint32 file_id = 3;</code>
       * @param value The fileId to set.
       * @return This builder for chaining.
       */
      public Builder setFileId(int value) {
        copyOnWrite();
        instance.setFileId(value);
        return this;
      }
      /**
       * <code>optional uint32 file_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileId() {
        copyOnWrite();
        instance.clearFileId();
        return this;
      }

      /**
       * <code>optional string file_name = 4;</code>
       * @return Whether the fileName field is set.
       */
      @java.lang.Override
      public boolean hasFileName() {
        return instance.hasFileName();
      }
      /**
       * <code>optional string file_name = 4;</code>
       * @return The fileName.
       */
      @java.lang.Override
      public java.lang.String getFileName() {
        return instance.getFileName();
      }
      /**
       * <code>optional string file_name = 4;</code>
       * @return The bytes for fileName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        return instance.getFileNameBytes();
      }
      /**
       * <code>optional string file_name = 4;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        copyOnWrite();
        instance.setFileName(value);
        return this;
      }
      /**
       * <code>optional string file_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        copyOnWrite();
        instance.clearFileName();
        return this;
      }
      /**
       * <code>optional string file_name = 4;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFileNameBytes(value);
        return this;
      }

      /**
       * <code>optional uint32 file_verify_val = 7;</code>
       * @return Whether the fileVerifyVal field is set.
       */
      @java.lang.Override
      public boolean hasFileVerifyVal() {
        return instance.hasFileVerifyVal();
      }
      /**
       * <code>optional uint32 file_verify_val = 7;</code>
       * @return The fileVerifyVal.
       */
      @java.lang.Override
      public int getFileVerifyVal() {
        return instance.getFileVerifyVal();
      }
      /**
       * <code>optional uint32 file_verify_val = 7;</code>
       * @param value The fileVerifyVal to set.
       * @return This builder for chaining.
       */
      public Builder setFileVerifyVal(int value) {
        copyOnWrite();
        instance.setFileVerifyVal(value);
        return this;
      }
      /**
       * <code>optional uint32 file_verify_val = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileVerifyVal() {
        copyOnWrite();
        instance.clearFileVerifyVal();
        return this;
      }

      /**
       * <code>optional uint32 file_crc32 = 8;</code>
       * @return Whether the fileCrc32 field is set.
       */
      @java.lang.Override
      public boolean hasFileCrc32() {
        return instance.hasFileCrc32();
      }
      /**
       * <code>optional uint32 file_crc32 = 8;</code>
       * @return The fileCrc32.
       */
      @java.lang.Override
      public int getFileCrc32() {
        return instance.getFileCrc32();
      }
      /**
       * <code>optional uint32 file_crc32 = 8;</code>
       * @param value The fileCrc32 to set.
       * @return This builder for chaining.
       */
      public Builder setFileCrc32(int value) {
        copyOnWrite();
        instance.setFileCrc32(value);
        return this;
      }
      /**
       * <code>optional uint32 file_crc32 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileCrc32() {
        copyOnWrite();
        instance.clearFileCrc32();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:file_download)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "fileSize_",
              "fileType_",
              "fileId_",
              "fileName_",
              "fileVerifyVal_",
              "fileCrc32_",
            };
            java.lang.String info =
                "\u0001\u0006\u0000\u0001\u0001\b\u0006\u0000\u0000\u0001\u0001\u150b\u0000\u0002" +
                "\u100b\u0001\u0003\u100b\u0002\u0004\u1008\u0003\u0007\u100b\u0004\b\u100b\u0005" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:file_download)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download DEFAULT_INSTANCE;
    static {
      file_download defaultInstance = new file_download();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        file_download.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.FileDownload.file_download getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<file_download> PARSER;

    public static com.google.protobuf.Parser<file_download> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
