// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: igpsport/map_new.proto

package nodomain.freeyourgadget.gadgetbridge.proto.igpsport;

public final class MapNew {
  private MapNew() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code map_op_type}
   */
  public enum map_op_type
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>MAP_OP_INVALID = 0;</code>
     */
    MAP_OP_INVALID(0),
    /**
     * <code>MAP_OP_LIST_NUM_GET = 1;</code>
     */
    MAP_OP_LIST_NUM_GET(1),
    /**
     * <code>MAP_OP_LIST_GET = 2;</code>
     */
    MAP_OP_LIST_GET(2),
    /**
     * <code>MAP_OP_DOWNLOAD = 3;</code>
     */
    MAP_OP_DOWNLOAD(3),
    /**
     * <code>MAP_OP_UPDATE = 4;</code>
     */
    MAP_OP_UPDATE(4),
    /**
     * <code>MAP_OP_DELETE = 5;</code>
     */
    MAP_OP_DELETE(5),
    /**
     * <code>MAP_OP_SET = 6;</code>
     */
    MAP_OP_SET(6),
    ;

    /**
     * <code>MAP_OP_INVALID = 0;</code>
     */
    public static final int MAP_OP_INVALID_VALUE = 0;
    /**
     * <code>MAP_OP_LIST_NUM_GET = 1;</code>
     */
    public static final int MAP_OP_LIST_NUM_GET_VALUE = 1;
    /**
     * <code>MAP_OP_LIST_GET = 2;</code>
     */
    public static final int MAP_OP_LIST_GET_VALUE = 2;
    /**
     * <code>MAP_OP_DOWNLOAD = 3;</code>
     */
    public static final int MAP_OP_DOWNLOAD_VALUE = 3;
    /**
     * <code>MAP_OP_UPDATE = 4;</code>
     */
    public static final int MAP_OP_UPDATE_VALUE = 4;
    /**
     * <code>MAP_OP_DELETE = 5;</code>
     */
    public static final int MAP_OP_DELETE_VALUE = 5;
    /**
     * <code>MAP_OP_SET = 6;</code>
     */
    public static final int MAP_OP_SET_VALUE = 6;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static map_op_type valueOf(int value) {
      return forNumber(value);
    }

    public static map_op_type forNumber(int value) {
      switch (value) {
        case 0: return MAP_OP_INVALID;
        case 1: return MAP_OP_LIST_NUM_GET;
        case 2: return MAP_OP_LIST_GET;
        case 3: return MAP_OP_DOWNLOAD;
        case 4: return MAP_OP_UPDATE;
        case 5: return MAP_OP_DELETE;
        case 6: return MAP_OP_SET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<map_op_type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        map_op_type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<map_op_type>() {
            @java.lang.Override
            public map_op_type findValueByNumber(int number) {
              return map_op_type.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return map_op_typeVerifier.INSTANCE;
    }

    private static final class map_op_typeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new map_op_typeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return map_op_type.forNumber(number) != null;
            }
          };

    private final int value;

    private map_op_type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:map_op_type)
  }

  /**
   * Protobuf enum {@code map_op_state}
   */
  public enum map_op_state
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>MAP_OP_STATE_INVALID = 0;</code>
     */
    MAP_OP_STATE_INVALID(0),
    /**
     * <code>MAP_OP_STATE_START = 1;</code>
     */
    MAP_OP_STATE_START(1),
    /**
     * <code>MAP_OP_STATE_END = 2;</code>
     */
    MAP_OP_STATE_END(2),
    ;

    /**
     * <code>MAP_OP_STATE_INVALID = 0;</code>
     */
    public static final int MAP_OP_STATE_INVALID_VALUE = 0;
    /**
     * <code>MAP_OP_STATE_START = 1;</code>
     */
    public static final int MAP_OP_STATE_START_VALUE = 1;
    /**
     * <code>MAP_OP_STATE_END = 2;</code>
     */
    public static final int MAP_OP_STATE_END_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static map_op_state valueOf(int value) {
      return forNumber(value);
    }

    public static map_op_state forNumber(int value) {
      switch (value) {
        case 0: return MAP_OP_STATE_INVALID;
        case 1: return MAP_OP_STATE_START;
        case 2: return MAP_OP_STATE_END;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<map_op_state>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        map_op_state> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<map_op_state>() {
            @java.lang.Override
            public map_op_state findValueByNumber(int number) {
              return map_op_state.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return map_op_stateVerifier.INSTANCE;
    }

    private static final class map_op_stateVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new map_op_stateVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return map_op_state.forNumber(number) != null;
            }
          };

    private final int value;

    private map_op_state(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:map_op_state)
  }

  public interface map_list_messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:map_list_message)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string map_country_name = 1;</code>
     * @return Whether the mapCountryName field is set.
     */
    boolean hasMapCountryName();
    /**
     * <code>optional string map_country_name = 1;</code>
     * @return The mapCountryName.
     */
    java.lang.String getMapCountryName();
    /**
     * <code>optional string map_country_name = 1;</code>
     * @return The bytes for mapCountryName.
     */
    com.google.protobuf.ByteString
        getMapCountryNameBytes();

    /**
     * <code>optional uint32 map_id = 2;</code>
     * @return Whether the mapId field is set.
     */
    boolean hasMapId();
    /**
     * <code>optional uint32 map_id = 2;</code>
     * @return The mapId.
     */
    int getMapId();

    /**
     * <code>optional string map_coordinates = 3;</code>
     * @return Whether the mapCoordinates field is set.
     */
    boolean hasMapCoordinates();
    /**
     * <code>optional string map_coordinates = 3;</code>
     * @return The mapCoordinates.
     */
    java.lang.String getMapCoordinates();
    /**
     * <code>optional string map_coordinates = 3;</code>
     * @return The bytes for mapCoordinates.
     */
    com.google.protobuf.ByteString
        getMapCoordinatesBytes();
  }
  /**
   * Protobuf type {@code map_list_message}
   */
  public  static final class map_list_message extends
      com.google.protobuf.GeneratedMessageLite<
          map_list_message, map_list_message.Builder> implements
      // @@protoc_insertion_point(message_implements:map_list_message)
      map_list_messageOrBuilder {
    private map_list_message() {
      mapCountryName_ = "";
      mapCoordinates_ = "";
    }
    private int bitField0_;
    public static final int MAP_COUNTRY_NAME_FIELD_NUMBER = 1;
    private java.lang.String mapCountryName_;
    /**
     * <code>optional string map_country_name = 1;</code>
     * @return Whether the mapCountryName field is set.
     */
    @java.lang.Override
    public boolean hasMapCountryName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string map_country_name = 1;</code>
     * @return The mapCountryName.
     */
    @java.lang.Override
    public java.lang.String getMapCountryName() {
      return mapCountryName_;
    }
    /**
     * <code>optional string map_country_name = 1;</code>
     * @return The bytes for mapCountryName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMapCountryNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mapCountryName_);
    }
    /**
     * <code>optional string map_country_name = 1;</code>
     * @param value The mapCountryName to set.
     */
    private void setMapCountryName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      mapCountryName_ = value;
    }
    /**
     * <code>optional string map_country_name = 1;</code>
     */
    private void clearMapCountryName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      mapCountryName_ = getDefaultInstance().getMapCountryName();
    }
    /**
     * <code>optional string map_country_name = 1;</code>
     * @param value The bytes for mapCountryName to set.
     */
    private void setMapCountryNameBytes(
        com.google.protobuf.ByteString value) {
      mapCountryName_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int MAP_ID_FIELD_NUMBER = 2;
    private int mapId_;
    /**
     * <code>optional uint32 map_id = 2;</code>
     * @return Whether the mapId field is set.
     */
    @java.lang.Override
    public boolean hasMapId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 map_id = 2;</code>
     * @return The mapId.
     */
    @java.lang.Override
    public int getMapId() {
      return mapId_;
    }
    /**
     * <code>optional uint32 map_id = 2;</code>
     * @param value The mapId to set.
     */
    private void setMapId(int value) {
      bitField0_ |= 0x00000002;
      mapId_ = value;
    }
    /**
     * <code>optional uint32 map_id = 2;</code>
     */
    private void clearMapId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      mapId_ = 0;
    }

    public static final int MAP_COORDINATES_FIELD_NUMBER = 3;
    private java.lang.String mapCoordinates_;
    /**
     * <code>optional string map_coordinates = 3;</code>
     * @return Whether the mapCoordinates field is set.
     */
    @java.lang.Override
    public boolean hasMapCoordinates() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string map_coordinates = 3;</code>
     * @return The mapCoordinates.
     */
    @java.lang.Override
    public java.lang.String getMapCoordinates() {
      return mapCoordinates_;
    }
    /**
     * <code>optional string map_coordinates = 3;</code>
     * @return The bytes for mapCoordinates.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMapCoordinatesBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mapCoordinates_);
    }
    /**
     * <code>optional string map_coordinates = 3;</code>
     * @param value The mapCoordinates to set.
     */
    private void setMapCoordinates(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
      mapCoordinates_ = value;
    }
    /**
     * <code>optional string map_coordinates = 3;</code>
     */
    private void clearMapCoordinates() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mapCoordinates_ = getDefaultInstance().getMapCoordinates();
    }
    /**
     * <code>optional string map_coordinates = 3;</code>
     * @param value The bytes for mapCoordinates to set.
     */
    private void setMapCoordinatesBytes(
        com.google.protobuf.ByteString value) {
      mapCoordinates_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code map_list_message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message, Builder> implements
        // @@protoc_insertion_point(builder_implements:map_list_message)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_messageOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string map_country_name = 1;</code>
       * @return Whether the mapCountryName field is set.
       */
      @java.lang.Override
      public boolean hasMapCountryName() {
        return instance.hasMapCountryName();
      }
      /**
       * <code>optional string map_country_name = 1;</code>
       * @return The mapCountryName.
       */
      @java.lang.Override
      public java.lang.String getMapCountryName() {
        return instance.getMapCountryName();
      }
      /**
       * <code>optional string map_country_name = 1;</code>
       * @return The bytes for mapCountryName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMapCountryNameBytes() {
        return instance.getMapCountryNameBytes();
      }
      /**
       * <code>optional string map_country_name = 1;</code>
       * @param value The mapCountryName to set.
       * @return This builder for chaining.
       */
      public Builder setMapCountryName(
          java.lang.String value) {
        copyOnWrite();
        instance.setMapCountryName(value);
        return this;
      }
      /**
       * <code>optional string map_country_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMapCountryName() {
        copyOnWrite();
        instance.clearMapCountryName();
        return this;
      }
      /**
       * <code>optional string map_country_name = 1;</code>
       * @param value The bytes for mapCountryName to set.
       * @return This builder for chaining.
       */
      public Builder setMapCountryNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMapCountryNameBytes(value);
        return this;
      }

      /**
       * <code>optional uint32 map_id = 2;</code>
       * @return Whether the mapId field is set.
       */
      @java.lang.Override
      public boolean hasMapId() {
        return instance.hasMapId();
      }
      /**
       * <code>optional uint32 map_id = 2;</code>
       * @return The mapId.
       */
      @java.lang.Override
      public int getMapId() {
        return instance.getMapId();
      }
      /**
       * <code>optional uint32 map_id = 2;</code>
       * @param value The mapId to set.
       * @return This builder for chaining.
       */
      public Builder setMapId(int value) {
        copyOnWrite();
        instance.setMapId(value);
        return this;
      }
      /**
       * <code>optional uint32 map_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMapId() {
        copyOnWrite();
        instance.clearMapId();
        return this;
      }

      /**
       * <code>optional string map_coordinates = 3;</code>
       * @return Whether the mapCoordinates field is set.
       */
      @java.lang.Override
      public boolean hasMapCoordinates() {
        return instance.hasMapCoordinates();
      }
      /**
       * <code>optional string map_coordinates = 3;</code>
       * @return The mapCoordinates.
       */
      @java.lang.Override
      public java.lang.String getMapCoordinates() {
        return instance.getMapCoordinates();
      }
      /**
       * <code>optional string map_coordinates = 3;</code>
       * @return The bytes for mapCoordinates.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMapCoordinatesBytes() {
        return instance.getMapCoordinatesBytes();
      }
      /**
       * <code>optional string map_coordinates = 3;</code>
       * @param value The mapCoordinates to set.
       * @return This builder for chaining.
       */
      public Builder setMapCoordinates(
          java.lang.String value) {
        copyOnWrite();
        instance.setMapCoordinates(value);
        return this;
      }
      /**
       * <code>optional string map_coordinates = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMapCoordinates() {
        copyOnWrite();
        instance.clearMapCoordinates();
        return this;
      }
      /**
       * <code>optional string map_coordinates = 3;</code>
       * @param value The bytes for mapCoordinates to set.
       * @return This builder for chaining.
       */
      public Builder setMapCoordinatesBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMapCoordinatesBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:map_list_message)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "mapCountryName_",
              "mapId_",
              "mapCoordinates_",
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1008\u0000\u0002" +
                "\u100b\u0001\u0003\u1008\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:map_list_message)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message DEFAULT_INSTANCE;
    static {
      map_list_message defaultInstance = new map_list_message();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        map_list_message.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<map_list_message> PARSER;

    public static com.google.protobuf.Parser<map_list_message> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface map_new_msgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:map_new_msg)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
     * @return Whether the serviceType field is set.
     */
    boolean hasServiceType();
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
     * @return The serviceType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index getServiceType();

    /**
     * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
     * @return Whether the mapOpType field is set.
     */
    boolean hasMapOpType();
    /**
     * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
     * @return The mapOpType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_type getMapOpType();

    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    java.util.List<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message> 
        getMapListMsgList();
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message getMapListMsg(int index);
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    int getMapListMsgCount();

    /**
     * <code>optional .map_op_state map_op_sta = 4;</code>
     * @return Whether the mapOpSta field is set.
     */
    boolean hasMapOpSta();
    /**
     * <code>optional .map_op_state map_op_sta = 4;</code>
     * @return The mapOpSta.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_state getMapOpSta();

    /**
     * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
     * @return Whether the mapListGetMsg field is set.
     */
    boolean hasMapListGetMsg();
    /**
     * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
     * @return The mapListGetMsg.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message getMapListGetMsg();
  }
  /**
   * Protobuf type {@code map_new_msg}
   */
  public  static final class map_new_msg extends
      com.google.protobuf.GeneratedMessageLite<
          map_new_msg, map_new_msg.Builder> implements
      // @@protoc_insertion_point(message_implements:map_new_msg)
      map_new_msgOrBuilder {
    private map_new_msg() {
      serviceType_ = 22;
      mapListMsg_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int SERVICE_TYPE_FIELD_NUMBER = 1;
    private int serviceType_;
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
     * @return Whether the serviceType field is set.
     */
    @java.lang.Override
    public boolean hasServiceType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
     * @return The serviceType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index getServiceType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index.forNumber(serviceType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index.enum_SERVICE_TYPE_INDEX_MAP_NEW : result;
    }
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
     * @param value The serviceType to set.
     */
    private void setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index value) {
      serviceType_ = value.getNumber();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
     */
    private void clearServiceType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      serviceType_ = 22;
    }

    public static final int MAP_OP_TYPE_FIELD_NUMBER = 2;
    private int mapOpType_;
    /**
     * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
     * @return Whether the mapOpType field is set.
     */
    @java.lang.Override
    public boolean hasMapOpType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
     * @return The mapOpType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_type getMapOpType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_type result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_type.forNumber(mapOpType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_type.MAP_OP_INVALID : result;
    }
    /**
     * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
     * @param value The mapOpType to set.
     */
    private void setMapOpType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_type value) {
      mapOpType_ = value.getNumber();
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
     */
    private void clearMapOpType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      mapOpType_ = 0;
    }

    public static final int MAP_LIST_MSG_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message> mapListMsg_;
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    @java.lang.Override
    public java.util.List<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message> getMapListMsgList() {
      return mapListMsg_;
    }
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    public java.util.List<? extends nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_messageOrBuilder> 
        getMapListMsgOrBuilderList() {
      return mapListMsg_;
    }
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    @java.lang.Override
    public int getMapListMsgCount() {
      return mapListMsg_.size();
    }
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message getMapListMsg(int index) {
      return mapListMsg_.get(index);
    }
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_messageOrBuilder getMapListMsgOrBuilder(
        int index) {
      return mapListMsg_.get(index);
    }
    private void ensureMapListMsgIsMutable() {
      com.google.protobuf.Internal.ProtobufList<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message> tmp = mapListMsg_;
      if (!tmp.isModifiable()) {
        mapListMsg_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    private void setMapListMsg(
        int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message value) {
      value.getClass();
  ensureMapListMsgIsMutable();
      mapListMsg_.set(index, value);
    }
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    private void addMapListMsg(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message value) {
      value.getClass();
  ensureMapListMsgIsMutable();
      mapListMsg_.add(value);
    }
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    private void addMapListMsg(
        int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message value) {
      value.getClass();
  ensureMapListMsgIsMutable();
      mapListMsg_.add(index, value);
    }
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    private void addAllMapListMsg(
        java.lang.Iterable<? extends nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message> values) {
      ensureMapListMsgIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, mapListMsg_);
    }
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    private void clearMapListMsg() {
      mapListMsg_ = emptyProtobufList();
    }
    /**
     * <code>repeated .map_list_message map_list_msg = 3;</code>
     */
    private void removeMapListMsg(int index) {
      ensureMapListMsgIsMutable();
      mapListMsg_.remove(index);
    }

    public static final int MAP_OP_STA_FIELD_NUMBER = 4;
    private int mapOpSta_;
    /**
     * <code>optional .map_op_state map_op_sta = 4;</code>
     * @return Whether the mapOpSta field is set.
     */
    @java.lang.Override
    public boolean hasMapOpSta() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .map_op_state map_op_sta = 4;</code>
     * @return The mapOpSta.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_state getMapOpSta() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_state result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_state.forNumber(mapOpSta_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_state.MAP_OP_STATE_INVALID : result;
    }
    /**
     * <code>optional .map_op_state map_op_sta = 4;</code>
     * @param value The mapOpSta to set.
     */
    private void setMapOpSta(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_state value) {
      mapOpSta_ = value.getNumber();
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>optional .map_op_state map_op_sta = 4;</code>
     */
    private void clearMapOpSta() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mapOpSta_ = 0;
    }

    public static final int MAP_LIST_GET_MSG_FIELD_NUMBER = 5;
    private nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message mapListGetMsg_;
    /**
     * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
     */
    @java.lang.Override
    public boolean hasMapListGetMsg() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message getMapListGetMsg() {
      return mapListGetMsg_ == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message.getDefaultInstance() : mapListGetMsg_;
    }
    /**
     * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
     */
    private void setMapListGetMsg(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message value) {
      value.getClass();
  mapListGetMsg_ = value;
      bitField0_ |= 0x00000008;
      }
    /**
     * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeMapListGetMsg(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message value) {
      value.getClass();
  if (mapListGetMsg_ != null &&
          mapListGetMsg_ != nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message.getDefaultInstance()) {
        mapListGetMsg_ =
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message.newBuilder(mapListGetMsg_).mergeFrom(value).buildPartial();
      } else {
        mapListGetMsg_ = value;
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
     */
    private void clearMapListGetMsg() {  mapListGetMsg_ = null;
      bitField0_ = (bitField0_ & ~0x00000008);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code map_new_msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg, Builder> implements
        // @@protoc_insertion_point(builder_implements:map_new_msg)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msgOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
       * @return Whether the serviceType field is set.
       */
      @java.lang.Override
      public boolean hasServiceType() {
        return instance.hasServiceType();
      }
      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
       * @return The serviceType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index getServiceType() {
        return instance.getServiceType();
      }
      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
       * @param value The enum numeric value on the wire for serviceType to set.
       * @return This builder for chaining.
       */
      public Builder setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index value) {
        copyOnWrite();
        instance.setServiceType(value);
        return this;
      }
      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_MAP_NEW];</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceType() {
        copyOnWrite();
        instance.clearServiceType();
        return this;
      }

      /**
       * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
       * @return Whether the mapOpType field is set.
       */
      @java.lang.Override
      public boolean hasMapOpType() {
        return instance.hasMapOpType();
      }
      /**
       * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
       * @return The mapOpType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_type getMapOpType() {
        return instance.getMapOpType();
      }
      /**
       * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
       * @param value The enum numeric value on the wire for mapOpType to set.
       * @return This builder for chaining.
       */
      public Builder setMapOpType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_type value) {
        copyOnWrite();
        instance.setMapOpType(value);
        return this;
      }
      /**
       * <code>required .map_op_type map_op_type = 2 [default = MAP_OP_INVALID];</code>
       * @return This builder for chaining.
       */
      public Builder clearMapOpType() {
        copyOnWrite();
        instance.clearMapOpType();
        return this;
      }

      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      @java.lang.Override
      public java.util.List<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message> getMapListMsgList() {
        return java.util.Collections.unmodifiableList(
            instance.getMapListMsgList());
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      @java.lang.Override
      public int getMapListMsgCount() {
        return instance.getMapListMsgCount();
      }/**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message getMapListMsg(int index) {
        return instance.getMapListMsg(index);
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      public Builder setMapListMsg(
          int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message value) {
        copyOnWrite();
        instance.setMapListMsg(index, value);
        return this;
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      public Builder setMapListMsg(
          int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message.Builder builderForValue) {
        copyOnWrite();
        instance.setMapListMsg(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      public Builder addMapListMsg(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message value) {
        copyOnWrite();
        instance.addMapListMsg(value);
        return this;
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      public Builder addMapListMsg(
          int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message value) {
        copyOnWrite();
        instance.addMapListMsg(index, value);
        return this;
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      public Builder addMapListMsg(
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message.Builder builderForValue) {
        copyOnWrite();
        instance.addMapListMsg(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      public Builder addMapListMsg(
          int index, nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message.Builder builderForValue) {
        copyOnWrite();
        instance.addMapListMsg(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      public Builder addAllMapListMsg(
          java.lang.Iterable<? extends nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message> values) {
        copyOnWrite();
        instance.addAllMapListMsg(values);
        return this;
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      public Builder clearMapListMsg() {
        copyOnWrite();
        instance.clearMapListMsg();
        return this;
      }
      /**
       * <code>repeated .map_list_message map_list_msg = 3;</code>
       */
      public Builder removeMapListMsg(int index) {
        copyOnWrite();
        instance.removeMapListMsg(index);
        return this;
      }

      /**
       * <code>optional .map_op_state map_op_sta = 4;</code>
       * @return Whether the mapOpSta field is set.
       */
      @java.lang.Override
      public boolean hasMapOpSta() {
        return instance.hasMapOpSta();
      }
      /**
       * <code>optional .map_op_state map_op_sta = 4;</code>
       * @return The mapOpSta.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_state getMapOpSta() {
        return instance.getMapOpSta();
      }
      /**
       * <code>optional .map_op_state map_op_sta = 4;</code>
       * @param value The enum numeric value on the wire for mapOpSta to set.
       * @return This builder for chaining.
       */
      public Builder setMapOpSta(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_state value) {
        copyOnWrite();
        instance.setMapOpSta(value);
        return this;
      }
      /**
       * <code>optional .map_op_state map_op_sta = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMapOpSta() {
        copyOnWrite();
        instance.clearMapOpSta();
        return this;
      }

      /**
       * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
       */
      @java.lang.Override
      public boolean hasMapListGetMsg() {
        return instance.hasMapListGetMsg();
      }
      /**
       * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message getMapListGetMsg() {
        return instance.getMapListGetMsg();
      }
      /**
       * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
       */
      public Builder setMapListGetMsg(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message value) {
        copyOnWrite();
        instance.setMapListGetMsg(value);
        return this;
        }
      /**
       * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
       */
      public Builder setMapListGetMsg(
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message.Builder builderForValue) {
        copyOnWrite();
        instance.setMapListGetMsg(builderForValue.build());
        return this;
      }
      /**
       * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
       */
      public Builder mergeMapListGetMsg(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.file_list_get_message value) {
        copyOnWrite();
        instance.mergeMapListGetMsg(value);
        return this;
      }
      /**
       * <code>optional .file_list_get_message map_list_get_msg = 5;</code>
       */
      public Builder clearMapListGetMsg() {  copyOnWrite();
        instance.clearMapListGetMsg();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:map_new_msg)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "serviceType_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index.internalGetVerifier(),
              "mapOpType_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_type.internalGetVerifier(),
              "mapListMsg_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_list_message.class,
              "mapOpSta_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_op_state.internalGetVerifier(),
              "mapListGetMsg_",
            };
            java.lang.String info =
                "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0001\u0002\u0001\u150c\u0000\u0002" +
                "\u150c\u0001\u0003\u001b\u0004\u100c\u0002\u0005\u1009\u0003";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:map_new_msg)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg DEFAULT_INSTANCE;
    static {
      map_new_msg defaultInstance = new map_new_msg();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        map_new_msg.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.MapNew.map_new_msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<map_new_msg> PARSER;

    public static com.google.protobuf.Parser<map_new_msg> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
