// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: igpsport/peripheral_firmware.proto

package nodomain.freeyourgadget.gadgetbridge.proto.igpsport;

public final class PeripheralFirmware {
  private PeripheralFirmware() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code PERIPHERAL_FIRMWARE_SERVICE}
   */
  public enum PERIPHERAL_FIRMWARE_SERVICE
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>PFS_UNSPECIFIED = 0;</code>
     */
    PFS_UNSPECIFIED(0),
    /**
     * <code>PFS_ENTER_DFU = 1;</code>
     */
    PFS_ENTER_DFU(1),
    /**
     * <code>PFS_MCU_UPDATE = 2;</code>
     */
    PFS_MCU_UPDATE(2),
    /**
     * <code>PFS_FW_STATUS = 3;</code>
     */
    PFS_FW_STATUS(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PFS_UNSPECIFIED = 0;</code>
     */
    public static final int PFS_UNSPECIFIED_VALUE = 0;
    /**
     * <code>PFS_ENTER_DFU = 1;</code>
     */
    public static final int PFS_ENTER_DFU_VALUE = 1;
    /**
     * <code>PFS_MCU_UPDATE = 2;</code>
     */
    public static final int PFS_MCU_UPDATE_VALUE = 2;
    /**
     * <code>PFS_FW_STATUS = 3;</code>
     */
    public static final int PFS_FW_STATUS_VALUE = 3;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PERIPHERAL_FIRMWARE_SERVICE valueOf(int value) {
      return forNumber(value);
    }

    public static PERIPHERAL_FIRMWARE_SERVICE forNumber(int value) {
      switch (value) {
        case 0: return PFS_UNSPECIFIED;
        case 1: return PFS_ENTER_DFU;
        case 2: return PFS_MCU_UPDATE;
        case 3: return PFS_FW_STATUS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PERIPHERAL_FIRMWARE_SERVICE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PERIPHERAL_FIRMWARE_SERVICE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PERIPHERAL_FIRMWARE_SERVICE>() {
            @java.lang.Override
            public PERIPHERAL_FIRMWARE_SERVICE findValueByNumber(int number) {
              return PERIPHERAL_FIRMWARE_SERVICE.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return PERIPHERAL_FIRMWARE_SERVICEVerifier.INSTANCE;
    }

    private static final class PERIPHERAL_FIRMWARE_SERVICEVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PERIPHERAL_FIRMWARE_SERVICEVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return PERIPHERAL_FIRMWARE_SERVICE.forNumber(number) != null;
            }
          };

    private final int value;

    private PERIPHERAL_FIRMWARE_SERVICE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PERIPHERAL_FIRMWARE_SERVICE)
  }

  /**
   * Protobuf enum {@code PERIPHERAL_FIRMWARE_OPERATE}
   */
  public enum PERIPHERAL_FIRMWARE_OPERATE
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>PFO_UNSPECIFIED = 0;</code>
     */
    PFO_UNSPECIFIED(0),
    /**
     * <code>PFO_MCU_UPDATE_START = 1;</code>
     */
    PFO_MCU_UPDATE_START(1),
    /**
     * <code>PFO_MCU_UPDATE_PROCESS = 2;</code>
     */
    PFO_MCU_UPDATE_PROCESS(2),
    /**
     * <code>PFO_MCU_UPDATE_END = 3;</code>
     */
    PFO_MCU_UPDATE_END(3),
    /**
     * <code>PFO_MCU_UPDATE_ERROR = 4;</code>
     */
    PFO_MCU_UPDATE_ERROR(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PFO_UNSPECIFIED = 0;</code>
     */
    public static final int PFO_UNSPECIFIED_VALUE = 0;
    /**
     * <code>PFO_MCU_UPDATE_START = 1;</code>
     */
    public static final int PFO_MCU_UPDATE_START_VALUE = 1;
    /**
     * <code>PFO_MCU_UPDATE_PROCESS = 2;</code>
     */
    public static final int PFO_MCU_UPDATE_PROCESS_VALUE = 2;
    /**
     * <code>PFO_MCU_UPDATE_END = 3;</code>
     */
    public static final int PFO_MCU_UPDATE_END_VALUE = 3;
    /**
     * <code>PFO_MCU_UPDATE_ERROR = 4;</code>
     */
    public static final int PFO_MCU_UPDATE_ERROR_VALUE = 4;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PERIPHERAL_FIRMWARE_OPERATE valueOf(int value) {
      return forNumber(value);
    }

    public static PERIPHERAL_FIRMWARE_OPERATE forNumber(int value) {
      switch (value) {
        case 0: return PFO_UNSPECIFIED;
        case 1: return PFO_MCU_UPDATE_START;
        case 2: return PFO_MCU_UPDATE_PROCESS;
        case 3: return PFO_MCU_UPDATE_END;
        case 4: return PFO_MCU_UPDATE_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PERIPHERAL_FIRMWARE_OPERATE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PERIPHERAL_FIRMWARE_OPERATE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PERIPHERAL_FIRMWARE_OPERATE>() {
            @java.lang.Override
            public PERIPHERAL_FIRMWARE_OPERATE findValueByNumber(int number) {
              return PERIPHERAL_FIRMWARE_OPERATE.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return PERIPHERAL_FIRMWARE_OPERATEVerifier.INSTANCE;
    }

    private static final class PERIPHERAL_FIRMWARE_OPERATEVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PERIPHERAL_FIRMWARE_OPERATEVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return PERIPHERAL_FIRMWARE_OPERATE.forNumber(number) != null;
            }
          };

    private final int value;

    private PERIPHERAL_FIRMWARE_OPERATE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PERIPHERAL_FIRMWARE_OPERATE)
  }

  public interface peripheral_firmware_messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peripheral_firmware_message)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 bin_packet_size = 6;</code>
     * @return The binPacketSize.
     */
    int getBinPacketSize();

    /**
     * <code>bytes bin_packet_data = 7;</code>
     * @return The binPacketData.
     */
    com.google.protobuf.ByteString getBinPacketData();

    /**
     * <code>uint32 bin_total_size = 8;</code>
     * @return The binTotalSize.
     */
    int getBinTotalSize();
  }
  /**
   * Protobuf type {@code peripheral_firmware_message}
   */
  public  static final class peripheral_firmware_message extends
      com.google.protobuf.GeneratedMessageLite<
          peripheral_firmware_message, peripheral_firmware_message.Builder> implements
      // @@protoc_insertion_point(message_implements:peripheral_firmware_message)
      peripheral_firmware_messageOrBuilder {
    private peripheral_firmware_message() {
      binPacketData_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int BIN_PACKET_SIZE_FIELD_NUMBER = 6;
    private int binPacketSize_;
    /**
     * <code>uint32 bin_packet_size = 6;</code>
     * @return The binPacketSize.
     */
    @java.lang.Override
    public int getBinPacketSize() {
      return binPacketSize_;
    }
    /**
     * <code>uint32 bin_packet_size = 6;</code>
     * @param value The binPacketSize to set.
     */
    private void setBinPacketSize(int value) {
      
      binPacketSize_ = value;
    }
    /**
     * <code>uint32 bin_packet_size = 6;</code>
     */
    private void clearBinPacketSize() {
      
      binPacketSize_ = 0;
    }

    public static final int BIN_PACKET_DATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString binPacketData_;
    /**
     * <code>bytes bin_packet_data = 7;</code>
     * @return The binPacketData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBinPacketData() {
      return binPacketData_;
    }
    /**
     * <code>bytes bin_packet_data = 7;</code>
     * @param value The binPacketData to set.
     */
    private void setBinPacketData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      binPacketData_ = value;
    }
    /**
     * <code>bytes bin_packet_data = 7;</code>
     */
    private void clearBinPacketData() {
      
      binPacketData_ = getDefaultInstance().getBinPacketData();
    }

    public static final int BIN_TOTAL_SIZE_FIELD_NUMBER = 8;
    private int binTotalSize_;
    /**
     * <code>uint32 bin_total_size = 8;</code>
     * @return The binTotalSize.
     */
    @java.lang.Override
    public int getBinTotalSize() {
      return binTotalSize_;
    }
    /**
     * <code>uint32 bin_total_size = 8;</code>
     * @param value The binTotalSize to set.
     */
    private void setBinTotalSize(int value) {
      
      binTotalSize_ = value;
    }
    /**
     * <code>uint32 bin_total_size = 8;</code>
     */
    private void clearBinTotalSize() {
      
      binTotalSize_ = 0;
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code peripheral_firmware_message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message, Builder> implements
        // @@protoc_insertion_point(builder_implements:peripheral_firmware_message)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_messageOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 bin_packet_size = 6;</code>
       * @return The binPacketSize.
       */
      @java.lang.Override
      public int getBinPacketSize() {
        return instance.getBinPacketSize();
      }
      /**
       * <code>uint32 bin_packet_size = 6;</code>
       * @param value The binPacketSize to set.
       * @return This builder for chaining.
       */
      public Builder setBinPacketSize(int value) {
        copyOnWrite();
        instance.setBinPacketSize(value);
        return this;
      }
      /**
       * <code>uint32 bin_packet_size = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBinPacketSize() {
        copyOnWrite();
        instance.clearBinPacketSize();
        return this;
      }

      /**
       * <code>bytes bin_packet_data = 7;</code>
       * @return The binPacketData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBinPacketData() {
        return instance.getBinPacketData();
      }
      /**
       * <code>bytes bin_packet_data = 7;</code>
       * @param value The binPacketData to set.
       * @return This builder for chaining.
       */
      public Builder setBinPacketData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBinPacketData(value);
        return this;
      }
      /**
       * <code>bytes bin_packet_data = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearBinPacketData() {
        copyOnWrite();
        instance.clearBinPacketData();
        return this;
      }

      /**
       * <code>uint32 bin_total_size = 8;</code>
       * @return The binTotalSize.
       */
      @java.lang.Override
      public int getBinTotalSize() {
        return instance.getBinTotalSize();
      }
      /**
       * <code>uint32 bin_total_size = 8;</code>
       * @param value The binTotalSize to set.
       * @return This builder for chaining.
       */
      public Builder setBinTotalSize(int value) {
        copyOnWrite();
        instance.setBinTotalSize(value);
        return this;
      }
      /**
       * <code>uint32 bin_total_size = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBinTotalSize() {
        copyOnWrite();
        instance.clearBinTotalSize();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:peripheral_firmware_message)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "binPacketSize_",
              "binPacketData_",
              "binTotalSize_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0006\b\u0003\u0000\u0000\u0000\u0006\u000b\u0007\n\b\u000b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:peripheral_firmware_message)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message DEFAULT_INSTANCE;
    static {
      peripheral_firmware_message defaultInstance = new peripheral_firmware_message();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        peripheral_firmware_message.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<peripheral_firmware_message> PARSER;

    public static com.google.protobuf.Parser<peripheral_firmware_message> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface peripheral_firmware_formatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peripheral_firmware_format)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @return The enum numeric value on the wire for serviceType.
     */
    int getServiceTypeValue();
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @return The serviceType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE getServiceType();

    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @return The enum numeric value on the wire for operateType.
     */
    int getOperateTypeValue();
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @return The operateType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE getOperateType();

    /**
     * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
     * @return The enum numeric value on the wire for subServiceType.
     */
    int getSubServiceTypeValue();
    /**
     * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
     * @return The subServiceType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_SERVICE getSubServiceType();

    /**
     * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
     * @return The enum numeric value on the wire for subOperateType.
     */
    int getSubOperateTypeValue();
    /**
     * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
     * @return The subOperateType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_OPERATE getSubOperateType();

    /**
     * <code>.peripheral_firmware_message message = 5;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.peripheral_firmware_message message = 5;</code>
     * @return The message.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message getMessage();
  }
  /**
   * Protobuf type {@code peripheral_firmware_format}
   */
  public  static final class peripheral_firmware_format extends
      com.google.protobuf.GeneratedMessageLite<
          peripheral_firmware_format, peripheral_firmware_format.Builder> implements
      // @@protoc_insertion_point(message_implements:peripheral_firmware_format)
      peripheral_firmware_formatOrBuilder {
    private peripheral_firmware_format() {
    }
    public static final int SERVICE_TYPE_FIELD_NUMBER = 1;
    private int serviceType_;
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @return The enum numeric value on the wire for serviceType.
     */
    @java.lang.Override
    public int getServiceTypeValue() {
      return serviceType_;
    }
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @return The serviceType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE getServiceType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE.forNumber(serviceType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE.UNRECOGNIZED : result;
    }
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @param value The enum numeric value on the wire for serviceType to set.
     */
    private void setServiceTypeValue(int value) {
        serviceType_ = value;
    }
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @param value The serviceType to set.
     */
    private void setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE value) {
      serviceType_ = value.getNumber();
      
    }
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     */
    private void clearServiceType() {
      
      serviceType_ = 0;
    }

    public static final int OPERATE_TYPE_FIELD_NUMBER = 2;
    private int operateType_;
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @return The enum numeric value on the wire for operateType.
     */
    @java.lang.Override
    public int getOperateTypeValue() {
      return operateType_;
    }
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @return The operateType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE getOperateType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE.forNumber(operateType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE.UNRECOGNIZED : result;
    }
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @param value The enum numeric value on the wire for operateType to set.
     */
    private void setOperateTypeValue(int value) {
        operateType_ = value;
    }
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @param value The operateType to set.
     */
    private void setOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE value) {
      operateType_ = value.getNumber();
      
    }
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     */
    private void clearOperateType() {
      
      operateType_ = 0;
    }

    public static final int SUB_SERVICE_TYPE_FIELD_NUMBER = 3;
    private int subServiceType_;
    /**
     * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
     * @return The enum numeric value on the wire for subServiceType.
     */
    @java.lang.Override
    public int getSubServiceTypeValue() {
      return subServiceType_;
    }
    /**
     * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
     * @return The subServiceType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_SERVICE getSubServiceType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_SERVICE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_SERVICE.forNumber(subServiceType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_SERVICE.UNRECOGNIZED : result;
    }
    /**
     * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
     * @param value The enum numeric value on the wire for subServiceType to set.
     */
    private void setSubServiceTypeValue(int value) {
        subServiceType_ = value;
    }
    /**
     * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
     * @param value The subServiceType to set.
     */
    private void setSubServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_SERVICE value) {
      subServiceType_ = value.getNumber();
      
    }
    /**
     * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
     */
    private void clearSubServiceType() {
      
      subServiceType_ = 0;
    }

    public static final int SUB_OPERATE_TYPE_FIELD_NUMBER = 4;
    private int subOperateType_;
    /**
     * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
     * @return The enum numeric value on the wire for subOperateType.
     */
    @java.lang.Override
    public int getSubOperateTypeValue() {
      return subOperateType_;
    }
    /**
     * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
     * @return The subOperateType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_OPERATE getSubOperateType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_OPERATE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_OPERATE.forNumber(subOperateType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_OPERATE.UNRECOGNIZED : result;
    }
    /**
     * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
     * @param value The enum numeric value on the wire for subOperateType to set.
     */
    private void setSubOperateTypeValue(int value) {
        subOperateType_ = value;
    }
    /**
     * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
     * @param value The subOperateType to set.
     */
    private void setSubOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_OPERATE value) {
      subOperateType_ = value.getNumber();
      
    }
    /**
     * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
     */
    private void clearSubOperateType() {
      
      subOperateType_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    private nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message message_;
    /**
     * <code>.peripheral_firmware_message message = 5;</code>
     */
    @java.lang.Override
    public boolean hasMessage() {
      return message_ != null;
    }
    /**
     * <code>.peripheral_firmware_message message = 5;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message getMessage() {
      return message_ == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message.getDefaultInstance() : message_;
    }
    /**
     * <code>.peripheral_firmware_message message = 5;</code>
     */
    private void setMessage(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message value) {
      value.getClass();
  message_ = value;
      
      }
    /**
     * <code>.peripheral_firmware_message message = 5;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeMessage(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message value) {
      value.getClass();
  if (message_ != null &&
          message_ != nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message.getDefaultInstance()) {
        message_ =
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message.newBuilder(message_).mergeFrom(value).buildPartial();
      } else {
        message_ = value;
      }
      
    }
    /**
     * <code>.peripheral_firmware_message message = 5;</code>
     */
    private void clearMessage() {  message_ = null;
      
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code peripheral_firmware_format}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format, Builder> implements
        // @@protoc_insertion_point(builder_implements:peripheral_firmware_format)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_formatOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @return The enum numeric value on the wire for serviceType.
       */
      @java.lang.Override
      public int getServiceTypeValue() {
        return instance.getServiceTypeValue();
      }
      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @param value The serviceType to set.
       * @return This builder for chaining.
       */
      public Builder setServiceTypeValue(int value) {
        copyOnWrite();
        instance.setServiceTypeValue(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @return The serviceType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE getServiceType() {
        return instance.getServiceType();
      }
      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @param value The enum numeric value on the wire for serviceType to set.
       * @return This builder for chaining.
       */
      public Builder setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE value) {
        copyOnWrite();
        instance.setServiceType(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceType() {
        copyOnWrite();
        instance.clearServiceType();
        return this;
      }

      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @return The enum numeric value on the wire for operateType.
       */
      @java.lang.Override
      public int getOperateTypeValue() {
        return instance.getOperateTypeValue();
      }
      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @param value The operateType to set.
       * @return This builder for chaining.
       */
      public Builder setOperateTypeValue(int value) {
        copyOnWrite();
        instance.setOperateTypeValue(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @return The operateType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE getOperateType() {
        return instance.getOperateType();
      }
      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @param value The enum numeric value on the wire for operateType to set.
       * @return This builder for chaining.
       */
      public Builder setOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE value) {
        copyOnWrite();
        instance.setOperateType(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperateType() {
        copyOnWrite();
        instance.clearOperateType();
        return this;
      }

      /**
       * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
       * @return The enum numeric value on the wire for subServiceType.
       */
      @java.lang.Override
      public int getSubServiceTypeValue() {
        return instance.getSubServiceTypeValue();
      }
      /**
       * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
       * @param value The subServiceType to set.
       * @return This builder for chaining.
       */
      public Builder setSubServiceTypeValue(int value) {
        copyOnWrite();
        instance.setSubServiceTypeValue(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
       * @return The subServiceType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_SERVICE getSubServiceType() {
        return instance.getSubServiceType();
      }
      /**
       * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
       * @param value The enum numeric value on the wire for subServiceType to set.
       * @return This builder for chaining.
       */
      public Builder setSubServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_SERVICE value) {
        copyOnWrite();
        instance.setSubServiceType(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_FIRMWARE_SERVICE sub_service_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubServiceType() {
        copyOnWrite();
        instance.clearSubServiceType();
        return this;
      }

      /**
       * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
       * @return The enum numeric value on the wire for subOperateType.
       */
      @java.lang.Override
      public int getSubOperateTypeValue() {
        return instance.getSubOperateTypeValue();
      }
      /**
       * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
       * @param value The subOperateType to set.
       * @return This builder for chaining.
       */
      public Builder setSubOperateTypeValue(int value) {
        copyOnWrite();
        instance.setSubOperateTypeValue(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
       * @return The subOperateType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_OPERATE getSubOperateType() {
        return instance.getSubOperateType();
      }
      /**
       * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
       * @param value The enum numeric value on the wire for subOperateType to set.
       * @return This builder for chaining.
       */
      public Builder setSubOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.PERIPHERAL_FIRMWARE_OPERATE value) {
        copyOnWrite();
        instance.setSubOperateType(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_FIRMWARE_OPERATE sub_operate_type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubOperateType() {
        copyOnWrite();
        instance.clearSubOperateType();
        return this;
      }

      /**
       * <code>.peripheral_firmware_message message = 5;</code>
       */
      @java.lang.Override
      public boolean hasMessage() {
        return instance.hasMessage();
      }
      /**
       * <code>.peripheral_firmware_message message = 5;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>.peripheral_firmware_message message = 5;</code>
       */
      public Builder setMessage(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
        }
      /**
       * <code>.peripheral_firmware_message message = 5;</code>
       */
      public Builder setMessage(
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message.Builder builderForValue) {
        copyOnWrite();
        instance.setMessage(builderForValue.build());
        return this;
      }
      /**
       * <code>.peripheral_firmware_message message = 5;</code>
       */
      public Builder mergeMessage(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_message value) {
        copyOnWrite();
        instance.mergeMessage(value);
        return this;
      }
      /**
       * <code>.peripheral_firmware_message message = 5;</code>
       */
      public Builder clearMessage() {  copyOnWrite();
        instance.clearMessage();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:peripheral_firmware_format)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "serviceType_",
              "operateType_",
              "subServiceType_",
              "subOperateType_",
              "message_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\f\u0002\f\u0003" +
                "\f\u0004\f\u0005\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:peripheral_firmware_format)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format DEFAULT_INSTANCE;
    static {
      peripheral_firmware_format defaultInstance = new peripheral_firmware_format();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        peripheral_firmware_format.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralFirmware.peripheral_firmware_format getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<peripheral_firmware_format> PARSER;

    public static com.google.protobuf.Parser<peripheral_firmware_format> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
