// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: igpsport/peripheral_oem.proto

package nodomain.freeyourgadget.gadgetbridge.proto.igpsport;

public final class PeripheralOem {
  private PeripheralOem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code PERIPHERAL_OEM_SERVICE}
   */
  public enum PERIPHERAL_OEM_SERVICE
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>POS_UNSPECIFIED = 0;</code>
     */
    POS_UNSPECIFIED(0),
    /**
     * <code>POS_BLE_INFO = 1;</code>
     */
    POS_BLE_INFO(1),
    /**
     * <code>POS_DEVICE_INFO = 2;</code>
     */
    POS_DEVICE_INFO(2),
    /**
     * <code>POS_MANUFACTURER_INFO = 3;</code>
     */
    POS_MANUFACTURER_INFO(3),
    /**
     * <code>POS_ALL_OEM = 11;</code>
     */
    POS_ALL_OEM(11),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>POS_UNSPECIFIED = 0;</code>
     */
    public static final int POS_UNSPECIFIED_VALUE = 0;
    /**
     * <code>POS_BLE_INFO = 1;</code>
     */
    public static final int POS_BLE_INFO_VALUE = 1;
    /**
     * <code>POS_DEVICE_INFO = 2;</code>
     */
    public static final int POS_DEVICE_INFO_VALUE = 2;
    /**
     * <code>POS_MANUFACTURER_INFO = 3;</code>
     */
    public static final int POS_MANUFACTURER_INFO_VALUE = 3;
    /**
     * <code>POS_ALL_OEM = 11;</code>
     */
    public static final int POS_ALL_OEM_VALUE = 11;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PERIPHERAL_OEM_SERVICE valueOf(int value) {
      return forNumber(value);
    }

    public static PERIPHERAL_OEM_SERVICE forNumber(int value) {
      switch (value) {
        case 0: return POS_UNSPECIFIED;
        case 1: return POS_BLE_INFO;
        case 2: return POS_DEVICE_INFO;
        case 3: return POS_MANUFACTURER_INFO;
        case 11: return POS_ALL_OEM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PERIPHERAL_OEM_SERVICE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PERIPHERAL_OEM_SERVICE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PERIPHERAL_OEM_SERVICE>() {
            @java.lang.Override
            public PERIPHERAL_OEM_SERVICE findValueByNumber(int number) {
              return PERIPHERAL_OEM_SERVICE.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return PERIPHERAL_OEM_SERVICEVerifier.INSTANCE;
    }

    private static final class PERIPHERAL_OEM_SERVICEVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PERIPHERAL_OEM_SERVICEVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return PERIPHERAL_OEM_SERVICE.forNumber(number) != null;
            }
          };

    private final int value;

    private PERIPHERAL_OEM_SERVICE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PERIPHERAL_OEM_SERVICE)
  }

  /**
   * Protobuf enum {@code PERIPHERAL_OEM_OPERATE}
   */
  public enum PERIPHERAL_OEM_OPERATE
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>POO_UNSPECIFIED = 0;</code>
     */
    POO_UNSPECIFIED(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>POO_UNSPECIFIED = 0;</code>
     */
    public static final int POO_UNSPECIFIED_VALUE = 0;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PERIPHERAL_OEM_OPERATE valueOf(int value) {
      return forNumber(value);
    }

    public static PERIPHERAL_OEM_OPERATE forNumber(int value) {
      switch (value) {
        case 0: return POO_UNSPECIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PERIPHERAL_OEM_OPERATE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PERIPHERAL_OEM_OPERATE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PERIPHERAL_OEM_OPERATE>() {
            @java.lang.Override
            public PERIPHERAL_OEM_OPERATE findValueByNumber(int number) {
              return PERIPHERAL_OEM_OPERATE.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return PERIPHERAL_OEM_OPERATEVerifier.INSTANCE;
    }

    private static final class PERIPHERAL_OEM_OPERATEVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PERIPHERAL_OEM_OPERATEVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return PERIPHERAL_OEM_OPERATE.forNumber(number) != null;
            }
          };

    private final int value;

    private PERIPHERAL_OEM_OPERATE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PERIPHERAL_OEM_OPERATE)
  }

  public interface peripheral_oem_data_bleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peripheral_oem_data_ble)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code peripheral_oem_data_ble}
   */
  public  static final class peripheral_oem_data_ble extends
      com.google.protobuf.GeneratedMessageLite<
          peripheral_oem_data_ble, peripheral_oem_data_ble.Builder> implements
      // @@protoc_insertion_point(message_implements:peripheral_oem_data_ble)
      peripheral_oem_data_bleOrBuilder {
    private peripheral_oem_data_ble() {
      name_ = "";
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code peripheral_oem_data_ble}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble, Builder> implements
        // @@protoc_insertion_point(builder_implements:peripheral_oem_data_ble)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_bleOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:peripheral_oem_data_ble)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "name_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:peripheral_oem_data_ble)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble DEFAULT_INSTANCE;
    static {
      peripheral_oem_data_ble defaultInstance = new peripheral_oem_data_ble();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        peripheral_oem_data_ble.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<peripheral_oem_data_ble> PARSER;

    public static com.google.protobuf.Parser<peripheral_oem_data_ble> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface peripheral_oem_data_deviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peripheral_oem_data_device)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
     * @return The enum numeric value on the wire for model.
     */
    int getModelValue();
    /**
     * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
     * @return The model.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralInfo.PERIPHERAL_INFO_MODEL_TYPE getModel();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 id = 3;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code peripheral_oem_data_device}
   */
  public  static final class peripheral_oem_data_device extends
      com.google.protobuf.GeneratedMessageLite<
          peripheral_oem_data_device, peripheral_oem_data_device.Builder> implements
      // @@protoc_insertion_point(message_implements:peripheral_oem_data_device)
      peripheral_oem_data_deviceOrBuilder {
    private peripheral_oem_data_device() {
      name_ = "";
    }
    public static final int MODEL_FIELD_NUMBER = 1;
    private int model_;
    /**
     * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
     * @return The enum numeric value on the wire for model.
     */
    @java.lang.Override
    public int getModelValue() {
      return model_;
    }
    /**
     * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
     * @return The model.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralInfo.PERIPHERAL_INFO_MODEL_TYPE getModel() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralInfo.PERIPHERAL_INFO_MODEL_TYPE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralInfo.PERIPHERAL_INFO_MODEL_TYPE.forNumber(model_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralInfo.PERIPHERAL_INFO_MODEL_TYPE.UNRECOGNIZED : result;
    }
    /**
     * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
     * @param value The enum numeric value on the wire for model to set.
     */
    private void setModelValue(int value) {
        model_ = value;
    }
    /**
     * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
     * @param value The model to set.
     */
    private void setModel(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralInfo.PERIPHERAL_INFO_MODEL_TYPE value) {
      model_ = value.getNumber();
      
    }
    /**
     * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
     */
    private void clearModel() {
      
      model_ = 0;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>uint32 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 3;</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>uint32 id = 3;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code peripheral_oem_data_device}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device, Builder> implements
        // @@protoc_insertion_point(builder_implements:peripheral_oem_data_device)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_deviceOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
       * @return The enum numeric value on the wire for model.
       */
      @java.lang.Override
      public int getModelValue() {
        return instance.getModelValue();
      }
      /**
       * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
       * @param value The model to set.
       * @return This builder for chaining.
       */
      public Builder setModelValue(int value) {
        copyOnWrite();
        instance.setModelValue(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
       * @return The model.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralInfo.PERIPHERAL_INFO_MODEL_TYPE getModel() {
        return instance.getModel();
      }
      /**
       * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
       * @param value The enum numeric value on the wire for model to set.
       * @return This builder for chaining.
       */
      public Builder setModel(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralInfo.PERIPHERAL_INFO_MODEL_TYPE value) {
        copyOnWrite();
        instance.setModel(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_INFO_MODEL_TYPE model = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearModel() {
        copyOnWrite();
        instance.clearModel();
        return this;
      }

      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>uint32 id = 3;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>uint32 id = 3;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>uint32 id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:peripheral_oem_data_device)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "model_",
              "name_",
              "id_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                "\u0003\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:peripheral_oem_data_device)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device DEFAULT_INSTANCE;
    static {
      peripheral_oem_data_device defaultInstance = new peripheral_oem_data_device();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        peripheral_oem_data_device.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<peripheral_oem_data_device> PARSER;

    public static com.google.protobuf.Parser<peripheral_oem_data_device> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface peripheral_oem_data_manufacturerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peripheral_oem_data_manufacturer)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 id = 2;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code peripheral_oem_data_manufacturer}
   */
  public  static final class peripheral_oem_data_manufacturer extends
      com.google.protobuf.GeneratedMessageLite<
          peripheral_oem_data_manufacturer, peripheral_oem_data_manufacturer.Builder> implements
      // @@protoc_insertion_point(message_implements:peripheral_oem_data_manufacturer)
      peripheral_oem_data_manufacturerOrBuilder {
    private peripheral_oem_data_manufacturer() {
      name_ = "";
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>uint32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 2;</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>uint32 id = 2;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code peripheral_oem_data_manufacturer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer, Builder> implements
        // @@protoc_insertion_point(builder_implements:peripheral_oem_data_manufacturer)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturerOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>uint32 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>uint32 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>uint32 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:peripheral_oem_data_manufacturer)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "name_",
              "id_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u000b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:peripheral_oem_data_manufacturer)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer DEFAULT_INSTANCE;
    static {
      peripheral_oem_data_manufacturer defaultInstance = new peripheral_oem_data_manufacturer();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        peripheral_oem_data_manufacturer.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<peripheral_oem_data_manufacturer> PARSER;

    public static com.google.protobuf.Parser<peripheral_oem_data_manufacturer> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface peripheral_oem_messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peripheral_oem_message)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.peripheral_oem_data_ble ble_info = 1;</code>
     * @return Whether the bleInfo field is set.
     */
    boolean hasBleInfo();
    /**
     * <code>.peripheral_oem_data_ble ble_info = 1;</code>
     * @return The bleInfo.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble getBleInfo();

    /**
     * <code>.peripheral_oem_data_device device_info = 2;</code>
     * @return Whether the deviceInfo field is set.
     */
    boolean hasDeviceInfo();
    /**
     * <code>.peripheral_oem_data_device device_info = 2;</code>
     * @return The deviceInfo.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device getDeviceInfo();

    /**
     * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
     * @return Whether the manufacturerInfo field is set.
     */
    boolean hasManufacturerInfo();
    /**
     * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
     * @return The manufacturerInfo.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer getManufacturerInfo();
  }
  /**
   * Protobuf type {@code peripheral_oem_message}
   */
  public  static final class peripheral_oem_message extends
      com.google.protobuf.GeneratedMessageLite<
          peripheral_oem_message, peripheral_oem_message.Builder> implements
      // @@protoc_insertion_point(message_implements:peripheral_oem_message)
      peripheral_oem_messageOrBuilder {
    private peripheral_oem_message() {
    }
    public static final int BLE_INFO_FIELD_NUMBER = 1;
    private nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble bleInfo_;
    /**
     * <code>.peripheral_oem_data_ble ble_info = 1;</code>
     */
    @java.lang.Override
    public boolean hasBleInfo() {
      return bleInfo_ != null;
    }
    /**
     * <code>.peripheral_oem_data_ble ble_info = 1;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble getBleInfo() {
      return bleInfo_ == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble.getDefaultInstance() : bleInfo_;
    }
    /**
     * <code>.peripheral_oem_data_ble ble_info = 1;</code>
     */
    private void setBleInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble value) {
      value.getClass();
  bleInfo_ = value;
      
      }
    /**
     * <code>.peripheral_oem_data_ble ble_info = 1;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeBleInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble value) {
      value.getClass();
  if (bleInfo_ != null &&
          bleInfo_ != nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble.getDefaultInstance()) {
        bleInfo_ =
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble.newBuilder(bleInfo_).mergeFrom(value).buildPartial();
      } else {
        bleInfo_ = value;
      }
      
    }
    /**
     * <code>.peripheral_oem_data_ble ble_info = 1;</code>
     */
    private void clearBleInfo() {  bleInfo_ = null;
      
    }

    public static final int DEVICE_INFO_FIELD_NUMBER = 2;
    private nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device deviceInfo_;
    /**
     * <code>.peripheral_oem_data_device device_info = 2;</code>
     */
    @java.lang.Override
    public boolean hasDeviceInfo() {
      return deviceInfo_ != null;
    }
    /**
     * <code>.peripheral_oem_data_device device_info = 2;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device getDeviceInfo() {
      return deviceInfo_ == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device.getDefaultInstance() : deviceInfo_;
    }
    /**
     * <code>.peripheral_oem_data_device device_info = 2;</code>
     */
    private void setDeviceInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device value) {
      value.getClass();
  deviceInfo_ = value;
      
      }
    /**
     * <code>.peripheral_oem_data_device device_info = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeDeviceInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device value) {
      value.getClass();
  if (deviceInfo_ != null &&
          deviceInfo_ != nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device.getDefaultInstance()) {
        deviceInfo_ =
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device.newBuilder(deviceInfo_).mergeFrom(value).buildPartial();
      } else {
        deviceInfo_ = value;
      }
      
    }
    /**
     * <code>.peripheral_oem_data_device device_info = 2;</code>
     */
    private void clearDeviceInfo() {  deviceInfo_ = null;
      
    }

    public static final int MANUFACTURER_INFO_FIELD_NUMBER = 3;
    private nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer manufacturerInfo_;
    /**
     * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
     */
    @java.lang.Override
    public boolean hasManufacturerInfo() {
      return manufacturerInfo_ != null;
    }
    /**
     * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer getManufacturerInfo() {
      return manufacturerInfo_ == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer.getDefaultInstance() : manufacturerInfo_;
    }
    /**
     * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
     */
    private void setManufacturerInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer value) {
      value.getClass();
  manufacturerInfo_ = value;
      
      }
    /**
     * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeManufacturerInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer value) {
      value.getClass();
  if (manufacturerInfo_ != null &&
          manufacturerInfo_ != nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer.getDefaultInstance()) {
        manufacturerInfo_ =
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer.newBuilder(manufacturerInfo_).mergeFrom(value).buildPartial();
      } else {
        manufacturerInfo_ = value;
      }
      
    }
    /**
     * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
     */
    private void clearManufacturerInfo() {  manufacturerInfo_ = null;
      
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code peripheral_oem_message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message, Builder> implements
        // @@protoc_insertion_point(builder_implements:peripheral_oem_message)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_messageOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.peripheral_oem_data_ble ble_info = 1;</code>
       */
      @java.lang.Override
      public boolean hasBleInfo() {
        return instance.hasBleInfo();
      }
      /**
       * <code>.peripheral_oem_data_ble ble_info = 1;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble getBleInfo() {
        return instance.getBleInfo();
      }
      /**
       * <code>.peripheral_oem_data_ble ble_info = 1;</code>
       */
      public Builder setBleInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble value) {
        copyOnWrite();
        instance.setBleInfo(value);
        return this;
        }
      /**
       * <code>.peripheral_oem_data_ble ble_info = 1;</code>
       */
      public Builder setBleInfo(
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble.Builder builderForValue) {
        copyOnWrite();
        instance.setBleInfo(builderForValue.build());
        return this;
      }
      /**
       * <code>.peripheral_oem_data_ble ble_info = 1;</code>
       */
      public Builder mergeBleInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_ble value) {
        copyOnWrite();
        instance.mergeBleInfo(value);
        return this;
      }
      /**
       * <code>.peripheral_oem_data_ble ble_info = 1;</code>
       */
      public Builder clearBleInfo() {  copyOnWrite();
        instance.clearBleInfo();
        return this;
      }

      /**
       * <code>.peripheral_oem_data_device device_info = 2;</code>
       */
      @java.lang.Override
      public boolean hasDeviceInfo() {
        return instance.hasDeviceInfo();
      }
      /**
       * <code>.peripheral_oem_data_device device_info = 2;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device getDeviceInfo() {
        return instance.getDeviceInfo();
      }
      /**
       * <code>.peripheral_oem_data_device device_info = 2;</code>
       */
      public Builder setDeviceInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device value) {
        copyOnWrite();
        instance.setDeviceInfo(value);
        return this;
        }
      /**
       * <code>.peripheral_oem_data_device device_info = 2;</code>
       */
      public Builder setDeviceInfo(
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device.Builder builderForValue) {
        copyOnWrite();
        instance.setDeviceInfo(builderForValue.build());
        return this;
      }
      /**
       * <code>.peripheral_oem_data_device device_info = 2;</code>
       */
      public Builder mergeDeviceInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_device value) {
        copyOnWrite();
        instance.mergeDeviceInfo(value);
        return this;
      }
      /**
       * <code>.peripheral_oem_data_device device_info = 2;</code>
       */
      public Builder clearDeviceInfo() {  copyOnWrite();
        instance.clearDeviceInfo();
        return this;
      }

      /**
       * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
       */
      @java.lang.Override
      public boolean hasManufacturerInfo() {
        return instance.hasManufacturerInfo();
      }
      /**
       * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer getManufacturerInfo() {
        return instance.getManufacturerInfo();
      }
      /**
       * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
       */
      public Builder setManufacturerInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer value) {
        copyOnWrite();
        instance.setManufacturerInfo(value);
        return this;
        }
      /**
       * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
       */
      public Builder setManufacturerInfo(
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer.Builder builderForValue) {
        copyOnWrite();
        instance.setManufacturerInfo(builderForValue.build());
        return this;
      }
      /**
       * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
       */
      public Builder mergeManufacturerInfo(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_data_manufacturer value) {
        copyOnWrite();
        instance.mergeManufacturerInfo(value);
        return this;
      }
      /**
       * <code>.peripheral_oem_data_manufacturer manufacturer_info = 3;</code>
       */
      public Builder clearManufacturerInfo() {  copyOnWrite();
        instance.clearManufacturerInfo();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:peripheral_oem_message)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bleInfo_",
              "deviceInfo_",
              "manufacturerInfo_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\t\u0002\t\u0003" +
                "\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:peripheral_oem_message)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message DEFAULT_INSTANCE;
    static {
      peripheral_oem_message defaultInstance = new peripheral_oem_message();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        peripheral_oem_message.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<peripheral_oem_message> PARSER;

    public static com.google.protobuf.Parser<peripheral_oem_message> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface peripheral_oem_formatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peripheral_oem_format)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @return The enum numeric value on the wire for serviceType.
     */
    int getServiceTypeValue();
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @return The serviceType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE getServiceType();

    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @return The enum numeric value on the wire for operateType.
     */
    int getOperateTypeValue();
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @return The operateType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE getOperateType();

    /**
     * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
     * @return The enum numeric value on the wire for subServiceType.
     */
    int getSubServiceTypeValue();
    /**
     * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
     * @return The subServiceType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_SERVICE getSubServiceType();

    /**
     * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
     * @return The enum numeric value on the wire for subOperateType.
     */
    int getSubOperateTypeValue();
    /**
     * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
     * @return The subOperateType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_OPERATE getSubOperateType();

    /**
     * <code>.peripheral_oem_message message = 5;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.peripheral_oem_message message = 5;</code>
     * @return The message.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message getMessage();
  }
  /**
   * Protobuf type {@code peripheral_oem_format}
   */
  public  static final class peripheral_oem_format extends
      com.google.protobuf.GeneratedMessageLite<
          peripheral_oem_format, peripheral_oem_format.Builder> implements
      // @@protoc_insertion_point(message_implements:peripheral_oem_format)
      peripheral_oem_formatOrBuilder {
    private peripheral_oem_format() {
    }
    public static final int SERVICE_TYPE_FIELD_NUMBER = 1;
    private int serviceType_;
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @return The enum numeric value on the wire for serviceType.
     */
    @java.lang.Override
    public int getServiceTypeValue() {
      return serviceType_;
    }
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @return The serviceType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE getServiceType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE.forNumber(serviceType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE.UNRECOGNIZED : result;
    }
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @param value The enum numeric value on the wire for serviceType to set.
     */
    private void setServiceTypeValue(int value) {
        serviceType_ = value;
    }
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     * @param value The serviceType to set.
     */
    private void setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE value) {
      serviceType_ = value.getNumber();
      
    }
    /**
     * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
     */
    private void clearServiceType() {
      
      serviceType_ = 0;
    }

    public static final int OPERATE_TYPE_FIELD_NUMBER = 2;
    private int operateType_;
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @return The enum numeric value on the wire for operateType.
     */
    @java.lang.Override
    public int getOperateTypeValue() {
      return operateType_;
    }
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @return The operateType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE getOperateType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE.forNumber(operateType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE.UNRECOGNIZED : result;
    }
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @param value The enum numeric value on the wire for operateType to set.
     */
    private void setOperateTypeValue(int value) {
        operateType_ = value;
    }
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     * @param value The operateType to set.
     */
    private void setOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE value) {
      operateType_ = value.getNumber();
      
    }
    /**
     * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
     */
    private void clearOperateType() {
      
      operateType_ = 0;
    }

    public static final int SUB_SERVICE_TYPE_FIELD_NUMBER = 3;
    private int subServiceType_;
    /**
     * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
     * @return The enum numeric value on the wire for subServiceType.
     */
    @java.lang.Override
    public int getSubServiceTypeValue() {
      return subServiceType_;
    }
    /**
     * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
     * @return The subServiceType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_SERVICE getSubServiceType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_SERVICE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_SERVICE.forNumber(subServiceType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_SERVICE.UNRECOGNIZED : result;
    }
    /**
     * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
     * @param value The enum numeric value on the wire for subServiceType to set.
     */
    private void setSubServiceTypeValue(int value) {
        subServiceType_ = value;
    }
    /**
     * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
     * @param value The subServiceType to set.
     */
    private void setSubServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_SERVICE value) {
      subServiceType_ = value.getNumber();
      
    }
    /**
     * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
     */
    private void clearSubServiceType() {
      
      subServiceType_ = 0;
    }

    public static final int SUB_OPERATE_TYPE_FIELD_NUMBER = 4;
    private int subOperateType_;
    /**
     * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
     * @return The enum numeric value on the wire for subOperateType.
     */
    @java.lang.Override
    public int getSubOperateTypeValue() {
      return subOperateType_;
    }
    /**
     * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
     * @return The subOperateType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_OPERATE getSubOperateType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_OPERATE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_OPERATE.forNumber(subOperateType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_OPERATE.UNRECOGNIZED : result;
    }
    /**
     * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
     * @param value The enum numeric value on the wire for subOperateType to set.
     */
    private void setSubOperateTypeValue(int value) {
        subOperateType_ = value;
    }
    /**
     * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
     * @param value The subOperateType to set.
     */
    private void setSubOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_OPERATE value) {
      subOperateType_ = value.getNumber();
      
    }
    /**
     * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
     */
    private void clearSubOperateType() {
      
      subOperateType_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    private nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message message_;
    /**
     * <code>.peripheral_oem_message message = 5;</code>
     */
    @java.lang.Override
    public boolean hasMessage() {
      return message_ != null;
    }
    /**
     * <code>.peripheral_oem_message message = 5;</code>
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message getMessage() {
      return message_ == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message.getDefaultInstance() : message_;
    }
    /**
     * <code>.peripheral_oem_message message = 5;</code>
     */
    private void setMessage(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message value) {
      value.getClass();
  message_ = value;
      
      }
    /**
     * <code>.peripheral_oem_message message = 5;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeMessage(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message value) {
      value.getClass();
  if (message_ != null &&
          message_ != nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message.getDefaultInstance()) {
        message_ =
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message.newBuilder(message_).mergeFrom(value).buildPartial();
      } else {
        message_ = value;
      }
      
    }
    /**
     * <code>.peripheral_oem_message message = 5;</code>
     */
    private void clearMessage() {  message_ = null;
      
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code peripheral_oem_format}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format, Builder> implements
        // @@protoc_insertion_point(builder_implements:peripheral_oem_format)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_formatOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @return The enum numeric value on the wire for serviceType.
       */
      @java.lang.Override
      public int getServiceTypeValue() {
        return instance.getServiceTypeValue();
      }
      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @param value The serviceType to set.
       * @return This builder for chaining.
       */
      public Builder setServiceTypeValue(int value) {
        copyOnWrite();
        instance.setServiceTypeValue(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @return The serviceType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE getServiceType() {
        return instance.getServiceType();
      }
      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @param value The enum numeric value on the wire for serviceType to set.
       * @return This builder for chaining.
       */
      public Builder setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_SERVICE_TYPE value) {
        copyOnWrite();
        instance.setServiceType(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_SERVICE_TYPE service_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceType() {
        copyOnWrite();
        instance.clearServiceType();
        return this;
      }

      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @return The enum numeric value on the wire for operateType.
       */
      @java.lang.Override
      public int getOperateTypeValue() {
        return instance.getOperateTypeValue();
      }
      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @param value The operateType to set.
       * @return This builder for chaining.
       */
      public Builder setOperateTypeValue(int value) {
        copyOnWrite();
        instance.setOperateTypeValue(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @return The operateType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE getOperateType() {
        return instance.getOperateType();
      }
      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @param value The enum numeric value on the wire for operateType to set.
       * @return This builder for chaining.
       */
      public Builder setOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralCommon.PERIPHERAL_OPERATE_TYPE value) {
        copyOnWrite();
        instance.setOperateType(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_OPERATE_TYPE operate_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperateType() {
        copyOnWrite();
        instance.clearOperateType();
        return this;
      }

      /**
       * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
       * @return The enum numeric value on the wire for subServiceType.
       */
      @java.lang.Override
      public int getSubServiceTypeValue() {
        return instance.getSubServiceTypeValue();
      }
      /**
       * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
       * @param value The subServiceType to set.
       * @return This builder for chaining.
       */
      public Builder setSubServiceTypeValue(int value) {
        copyOnWrite();
        instance.setSubServiceTypeValue(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
       * @return The subServiceType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_SERVICE getSubServiceType() {
        return instance.getSubServiceType();
      }
      /**
       * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
       * @param value The enum numeric value on the wire for subServiceType to set.
       * @return This builder for chaining.
       */
      public Builder setSubServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_SERVICE value) {
        copyOnWrite();
        instance.setSubServiceType(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_OEM_SERVICE sub_service_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubServiceType() {
        copyOnWrite();
        instance.clearSubServiceType();
        return this;
      }

      /**
       * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
       * @return The enum numeric value on the wire for subOperateType.
       */
      @java.lang.Override
      public int getSubOperateTypeValue() {
        return instance.getSubOperateTypeValue();
      }
      /**
       * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
       * @param value The subOperateType to set.
       * @return This builder for chaining.
       */
      public Builder setSubOperateTypeValue(int value) {
        copyOnWrite();
        instance.setSubOperateTypeValue(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
       * @return The subOperateType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_OPERATE getSubOperateType() {
        return instance.getSubOperateType();
      }
      /**
       * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
       * @param value The enum numeric value on the wire for subOperateType to set.
       * @return This builder for chaining.
       */
      public Builder setSubOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.PERIPHERAL_OEM_OPERATE value) {
        copyOnWrite();
        instance.setSubOperateType(value);
        return this;
      }
      /**
       * <code>.PERIPHERAL_OEM_OPERATE sub_operate_type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubOperateType() {
        copyOnWrite();
        instance.clearSubOperateType();
        return this;
      }

      /**
       * <code>.peripheral_oem_message message = 5;</code>
       */
      @java.lang.Override
      public boolean hasMessage() {
        return instance.hasMessage();
      }
      /**
       * <code>.peripheral_oem_message message = 5;</code>
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>.peripheral_oem_message message = 5;</code>
       */
      public Builder setMessage(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
        }
      /**
       * <code>.peripheral_oem_message message = 5;</code>
       */
      public Builder setMessage(
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message.Builder builderForValue) {
        copyOnWrite();
        instance.setMessage(builderForValue.build());
        return this;
      }
      /**
       * <code>.peripheral_oem_message message = 5;</code>
       */
      public Builder mergeMessage(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_message value) {
        copyOnWrite();
        instance.mergeMessage(value);
        return this;
      }
      /**
       * <code>.peripheral_oem_message message = 5;</code>
       */
      public Builder clearMessage() {  copyOnWrite();
        instance.clearMessage();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:peripheral_oem_format)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "serviceType_",
              "operateType_",
              "subServiceType_",
              "subOperateType_",
              "message_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\f\u0002\f\u0003" +
                "\f\u0004\f\u0005\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:peripheral_oem_format)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format DEFAULT_INSTANCE;
    static {
      peripheral_oem_format defaultInstance = new peripheral_oem_format();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        peripheral_oem_format.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.PeripheralOem.peripheral_oem_format getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<peripheral_oem_format> PARSER;

    public static com.google.protobuf.Parser<peripheral_oem_format> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
