// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: igpsport/train_plan.proto

package nodomain.freeyourgadget.gadgetbridge.proto.igpsport;

public final class TrainPlan {
  private TrainPlan() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code TRAINING_PLAN_OPERATE_TYPE}
   */
  public enum TRAINING_PLAN_OPERATE_TYPE
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_NONE = 0;</code>
     */
    enum_TRAINING_PLAN_OPERATE_TYPE_NONE(0),
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_NUM = 1;</code>
     */
    enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_NUM(1),
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_FILE = 2;</code>
     */
    enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_FILE(2),
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_START = 3;</code>
     */
    enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_START(3),
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_END = 4;</code>
     */
    enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_END(4),
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_UPDATE_SCHEDULE_STATE_INFO = 5;</code>
     */
    enum_TRAINING_PLAN_OPERATE_TYPE_UPDATE_SCHEDULE_STATE_INFO(5),
    ;

    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_NONE = 0;</code>
     */
    public static final int enum_TRAINING_PLAN_OPERATE_TYPE_NONE_VALUE = 0;
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_NUM = 1;</code>
     */
    public static final int enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_NUM_VALUE = 1;
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_FILE = 2;</code>
     */
    public static final int enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_FILE_VALUE = 2;
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_START = 3;</code>
     */
    public static final int enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_START_VALUE = 3;
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_END = 4;</code>
     */
    public static final int enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_END_VALUE = 4;
    /**
     * <code>enum_TRAINING_PLAN_OPERATE_TYPE_UPDATE_SCHEDULE_STATE_INFO = 5;</code>
     */
    public static final int enum_TRAINING_PLAN_OPERATE_TYPE_UPDATE_SCHEDULE_STATE_INFO_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TRAINING_PLAN_OPERATE_TYPE valueOf(int value) {
      return forNumber(value);
    }

    public static TRAINING_PLAN_OPERATE_TYPE forNumber(int value) {
      switch (value) {
        case 0: return enum_TRAINING_PLAN_OPERATE_TYPE_NONE;
        case 1: return enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_NUM;
        case 2: return enum_TRAINING_PLAN_OPERATE_TYPE_GET_SCHEDULE_FILE;
        case 3: return enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_START;
        case 4: return enum_TRAINING_PLAN_OPERATE_TYPE_SYNC_TRAINING_FILE_END;
        case 5: return enum_TRAINING_PLAN_OPERATE_TYPE_UPDATE_SCHEDULE_STATE_INFO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TRAINING_PLAN_OPERATE_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TRAINING_PLAN_OPERATE_TYPE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TRAINING_PLAN_OPERATE_TYPE>() {
            @java.lang.Override
            public TRAINING_PLAN_OPERATE_TYPE findValueByNumber(int number) {
              return TRAINING_PLAN_OPERATE_TYPE.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return TRAINING_PLAN_OPERATE_TYPEVerifier.INSTANCE;
    }

    private static final class TRAINING_PLAN_OPERATE_TYPEVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new TRAINING_PLAN_OPERATE_TYPEVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return TRAINING_PLAN_OPERATE_TYPE.forNumber(number) != null;
            }
          };

    private final int value;

    private TRAINING_PLAN_OPERATE_TYPE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TRAINING_PLAN_OPERATE_TYPE)
  }

  public interface schedule_data_msgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schedule_data_msg)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
     * @return Whether the serviceType field is set.
     */
    boolean hasServiceType();
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
     * @return The serviceType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index getServiceType();

    /**
     * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
     * @return Whether the scheduleDateOperateType field is set.
     */
    boolean hasScheduleDateOperateType();
    /**
     * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
     * @return The scheduleDateOperateType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.TRAINING_PLAN_OPERATE_TYPE getScheduleDateOperateType();

    /**
     * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
     * @return Whether the operateType field is set.
     */
    boolean hasOperateType();
    /**
     * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
     * @return The operateType.
     */
    nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.SERVICE_OPERATE_TYPE getOperateType();

    /**
     * <code>optional int32 file_number = 4;</code>
     * @return Whether the fileNumber field is set.
     */
    boolean hasFileNumber();
    /**
     * <code>optional int32 file_number = 4;</code>
     * @return The fileNumber.
     */
    int getFileNumber();

    /**
     * <code>optional int32 utc_time = 5;</code>
     * @return Whether the utcTime field is set.
     */
    boolean hasUtcTime();
    /**
     * <code>optional int32 utc_time = 5;</code>
     * @return The utcTime.
     */
    int getUtcTime();
  }
  /**
   * Protobuf type {@code schedule_data_msg}
   */
  public  static final class schedule_data_msg extends
      com.google.protobuf.GeneratedMessageLite<
          schedule_data_msg, schedule_data_msg.Builder> implements
      // @@protoc_insertion_point(message_implements:schedule_data_msg)
      schedule_data_msgOrBuilder {
    private schedule_data_msg() {
      serviceType_ = 25;
    }
    private int bitField0_;
    public static final int SERVICE_TYPE_FIELD_NUMBER = 1;
    private int serviceType_;
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
     * @return Whether the serviceType field is set.
     */
    @java.lang.Override
    public boolean hasServiceType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
     * @return The serviceType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index getServiceType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index.forNumber(serviceType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index.enum_SERVICE_TYPE_INDEX_TRAINING_PLAN : result;
    }
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
     * @param value The serviceType to set.
     */
    private void setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index value) {
      serviceType_ = value.getNumber();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
     */
    private void clearServiceType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      serviceType_ = 25;
    }

    public static final int SCHEDULE_DATE_OPERATE_TYPE_FIELD_NUMBER = 2;
    private int scheduleDateOperateType_;
    /**
     * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
     * @return Whether the scheduleDateOperateType field is set.
     */
    @java.lang.Override
    public boolean hasScheduleDateOperateType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
     * @return The scheduleDateOperateType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.TRAINING_PLAN_OPERATE_TYPE getScheduleDateOperateType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.TRAINING_PLAN_OPERATE_TYPE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.TRAINING_PLAN_OPERATE_TYPE.forNumber(scheduleDateOperateType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.TRAINING_PLAN_OPERATE_TYPE.enum_TRAINING_PLAN_OPERATE_TYPE_NONE : result;
    }
    /**
     * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
     * @param value The scheduleDateOperateType to set.
     */
    private void setScheduleDateOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.TRAINING_PLAN_OPERATE_TYPE value) {
      scheduleDateOperateType_ = value.getNumber();
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
     */
    private void clearScheduleDateOperateType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      scheduleDateOperateType_ = 0;
    }

    public static final int OPERATE_TYPE_FIELD_NUMBER = 3;
    private int operateType_;
    /**
     * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
     * @return Whether the operateType field is set.
     */
    @java.lang.Override
    public boolean hasOperateType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
     * @return The operateType.
     */
    @java.lang.Override
    public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.SERVICE_OPERATE_TYPE getOperateType() {
      nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.SERVICE_OPERATE_TYPE result = nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.SERVICE_OPERATE_TYPE.forNumber(operateType_);
      return result == null ? nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.SERVICE_OPERATE_TYPE.enum_SERVICE_OPERATE_TYPE_NONE : result;
    }
    /**
     * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
     * @param value The operateType to set.
     */
    private void setOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.SERVICE_OPERATE_TYPE value) {
      operateType_ = value.getNumber();
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
     */
    private void clearOperateType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      operateType_ = 0;
    }

    public static final int FILE_NUMBER_FIELD_NUMBER = 4;
    private int fileNumber_;
    /**
     * <code>optional int32 file_number = 4;</code>
     * @return Whether the fileNumber field is set.
     */
    @java.lang.Override
    public boolean hasFileNumber() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 file_number = 4;</code>
     * @return The fileNumber.
     */
    @java.lang.Override
    public int getFileNumber() {
      return fileNumber_;
    }
    /**
     * <code>optional int32 file_number = 4;</code>
     * @param value The fileNumber to set.
     */
    private void setFileNumber(int value) {
      bitField0_ |= 0x00000008;
      fileNumber_ = value;
    }
    /**
     * <code>optional int32 file_number = 4;</code>
     */
    private void clearFileNumber() {
      bitField0_ = (bitField0_ & ~0x00000008);
      fileNumber_ = 0;
    }

    public static final int UTC_TIME_FIELD_NUMBER = 5;
    private int utcTime_;
    /**
     * <code>optional int32 utc_time = 5;</code>
     * @return Whether the utcTime field is set.
     */
    @java.lang.Override
    public boolean hasUtcTime() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 utc_time = 5;</code>
     * @return The utcTime.
     */
    @java.lang.Override
    public int getUtcTime() {
      return utcTime_;
    }
    /**
     * <code>optional int32 utc_time = 5;</code>
     * @param value The utcTime to set.
     */
    private void setUtcTime(int value) {
      bitField0_ |= 0x00000010;
      utcTime_ = value;
    }
    /**
     * <code>optional int32 utc_time = 5;</code>
     */
    private void clearUtcTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      utcTime_ = 0;
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code schedule_data_msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg, Builder> implements
        // @@protoc_insertion_point(builder_implements:schedule_data_msg)
        nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msgOrBuilder {
      // Construct using nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
       * @return Whether the serviceType field is set.
       */
      @java.lang.Override
      public boolean hasServiceType() {
        return instance.hasServiceType();
      }
      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
       * @return The serviceType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index getServiceType() {
        return instance.getServiceType();
      }
      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
       * @param value The enum numeric value on the wire for serviceType to set.
       * @return This builder for chaining.
       */
      public Builder setServiceType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index value) {
        copyOnWrite();
        instance.setServiceType(value);
        return this;
      }
      /**
       * <code>required .service_type_index service_type = 1 [default = enum_SERVICE_TYPE_INDEX_TRAINING_PLAN];</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceType() {
        copyOnWrite();
        instance.clearServiceType();
        return this;
      }

      /**
       * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
       * @return Whether the scheduleDateOperateType field is set.
       */
      @java.lang.Override
      public boolean hasScheduleDateOperateType() {
        return instance.hasScheduleDateOperateType();
      }
      /**
       * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
       * @return The scheduleDateOperateType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.TRAINING_PLAN_OPERATE_TYPE getScheduleDateOperateType() {
        return instance.getScheduleDateOperateType();
      }
      /**
       * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
       * @param value The enum numeric value on the wire for scheduleDateOperateType to set.
       * @return This builder for chaining.
       */
      public Builder setScheduleDateOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.TRAINING_PLAN_OPERATE_TYPE value) {
        copyOnWrite();
        instance.setScheduleDateOperateType(value);
        return this;
      }
      /**
       * <code>required .TRAINING_PLAN_OPERATE_TYPE schedule_date_operate_type = 2 [default = enum_TRAINING_PLAN_OPERATE_TYPE_NONE];</code>
       * @return This builder for chaining.
       */
      public Builder clearScheduleDateOperateType() {
        copyOnWrite();
        instance.clearScheduleDateOperateType();
        return this;
      }

      /**
       * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
       * @return Whether the operateType field is set.
       */
      @java.lang.Override
      public boolean hasOperateType() {
        return instance.hasOperateType();
      }
      /**
       * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
       * @return The operateType.
       */
      @java.lang.Override
      public nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.SERVICE_OPERATE_TYPE getOperateType() {
        return instance.getOperateType();
      }
      /**
       * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
       * @param value The enum numeric value on the wire for operateType to set.
       * @return This builder for chaining.
       */
      public Builder setOperateType(nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.SERVICE_OPERATE_TYPE value) {
        copyOnWrite();
        instance.setOperateType(value);
        return this;
      }
      /**
       * <code>required .SERVICE_OPERATE_TYPE operate_type = 3 [default = enum_SERVICE_OPERATE_TYPE_NONE];</code>
       * @return This builder for chaining.
       */
      public Builder clearOperateType() {
        copyOnWrite();
        instance.clearOperateType();
        return this;
      }

      /**
       * <code>optional int32 file_number = 4;</code>
       * @return Whether the fileNumber field is set.
       */
      @java.lang.Override
      public boolean hasFileNumber() {
        return instance.hasFileNumber();
      }
      /**
       * <code>optional int32 file_number = 4;</code>
       * @return The fileNumber.
       */
      @java.lang.Override
      public int getFileNumber() {
        return instance.getFileNumber();
      }
      /**
       * <code>optional int32 file_number = 4;</code>
       * @param value The fileNumber to set.
       * @return This builder for chaining.
       */
      public Builder setFileNumber(int value) {
        copyOnWrite();
        instance.setFileNumber(value);
        return this;
      }
      /**
       * <code>optional int32 file_number = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileNumber() {
        copyOnWrite();
        instance.clearFileNumber();
        return this;
      }

      /**
       * <code>optional int32 utc_time = 5;</code>
       * @return Whether the utcTime field is set.
       */
      @java.lang.Override
      public boolean hasUtcTime() {
        return instance.hasUtcTime();
      }
      /**
       * <code>optional int32 utc_time = 5;</code>
       * @return The utcTime.
       */
      @java.lang.Override
      public int getUtcTime() {
        return instance.getUtcTime();
      }
      /**
       * <code>optional int32 utc_time = 5;</code>
       * @param value The utcTime to set.
       * @return This builder for chaining.
       */
      public Builder setUtcTime(int value) {
        copyOnWrite();
        instance.setUtcTime(value);
        return this;
      }
      /**
       * <code>optional int32 utc_time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUtcTime() {
        copyOnWrite();
        instance.clearUtcTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:schedule_data_msg)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "serviceType_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.service_type_index.internalGetVerifier(),
              "scheduleDateOperateType_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.TRAINING_PLAN_OPERATE_TYPE.internalGetVerifier(),
              "operateType_",
              nodomain.freeyourgadget.gadgetbridge.proto.igpsport.Common.SERVICE_OPERATE_TYPE.internalGetVerifier(),
              "fileNumber_",
              "utcTime_",
            };
            java.lang.String info =
                "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0003\u0001\u150c\u0000\u0002" +
                "\u150c\u0001\u0003\u150c\u0002\u0004\u1004\u0003\u0005\u1004\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg> parser = PARSER;
          if (parser == null) {
            synchronized (nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:schedule_data_msg)
    private static final nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg DEFAULT_INSTANCE;
    static {
      schedule_data_msg defaultInstance = new schedule_data_msg();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        schedule_data_msg.class, defaultInstance);
    }

    public static nodomain.freeyourgadget.gadgetbridge.proto.igpsport.TrainPlan.schedule_data_msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<schedule_data_msg> PARSER;

    public static com.google.protobuf.Parser<schedule_data_msg> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
