/*  Copyright (C) 2024-2026 José Rebelo, Daniele Gobbetti, Sebastian Dröge,
        punchdeerflyscorpion, Thomas Kuehne

    This file is part of Gadgetbridge.

    Gadgetbridge is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Gadgetbridge is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>. */
package nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.codegen;

import com.google.gson.FormattingStyle;
import com.google.gson.stream.JsonWriter;

import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONTokener;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.time.DayOfWeek;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public enum FitCodeGen {
    ;

    // message definitions repeatedly directly accessed
    // put everything else in functions to avoid "code to large" for the class constructor
    private static final int[] DIRECT_ACCESS_MESSAGES = {0, 1, 206};

    private static final String NATIVE_HEADER =
            """                        
                    package nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit;
                    
                    import static nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.baseTypes.BaseType.*;
                    import static nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.fieldDefinitions.FieldDefinitions.*;
                    import static nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.NativeFITMessage.FieldDefinitionPrimitive;
                    
                    import java.util.List;
                    import java.util.SortedMap;
                    import java.util.TreeMap;
                    
                    @SuppressWarnings("DuplicateStringLiteralInspection")
                    public enum NativeFITMessages {
                        DUMMY();""";

    private static final String AUTO_GENRATED = "/// WARNING: This file is auto-generated by {@link " + FitCodeGen.class.getCanonicalName() + "} and fit_profile.json!\n"
            + "/// Do NOT edit this file.";

    private static final String COPYRIGHT_HEADER = """
            /*  Copyright (C) 2026 Freeyourgadget
            
                This file is part of Gadgetbridge.
            
                Gadgetbridge is free software: you can redistribute it and/or modify
                it under the terms of the GNU Affero General Public License as published
                by the Free Software Foundation, either version 3 of the License, or
                (at your option) any later version.
            
                Gadgetbridge is distributed in the hope that it will be useful,
                but WITHOUT ANY WARRANTY; without even the implied warranty of
                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
                GNU Affero General Public License for more details.
            
                You should have received a copy of the GNU Affero General Public License
                along with this program.  If not, see <https://www.gnu.org/licenses/>. */
            """;

    private static final String ENUM_CREATION = """
                        case ${enumType} -> new FieldDefinition${enumType}(localNumber, size, baseType, name, scale, offset);
            """;

    private static final String FIELD_DEFINTION = """
            ${copyrightHeader}
            package nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.fieldDefinitions;
            
            import androidx.annotation.Nullable;
            
            import java.nio.ByteBuffer;
            
            import nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.FieldDefinition;
            import nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.baseTypes.BaseType;
            import nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.enums.${enumType};
            
            ${autoGenerated}
            
            public class FieldDefinition${enumType} extends FieldDefinition {
                public FieldDefinition${enumType}(int localNumber, int size, BaseType baseType, String name, final int scale, final int offset) {
                    super(localNumber, size, baseType, name, scale, offset);
                }
            
                @Nullable
                public static ${enumType} fromId(final int id) {
                    for (final ${enumType} candidate : ${enumType}.values()) {
                        if (id == candidate.num) {
                            return candidate;
                        }
                    }
                    return null;
                }
            
                @Nullable
                @Override
                public ${enumType} decode(final ByteBuffer byteBuffer) {
                    final Object rawObj = baseType.decode(byteBuffer, scale, offset);
                    if (rawObj instanceof final Number raw) {
                        final int id = raw.intValue();
                        return fromId(id);
                    }
                    return null;
                }
            
                @Override
                public void encode(final ByteBuffer byteBuffer, Object o) {
                    if (o instanceof final ${enumType} enumValue) {
                        o = enumValue.num;
                    }
                    baseType.encode(byteBuffer, o, scale, offset);
                }
            }
            """;

    private static final String FIELD_DEFINITIONS = """
            ${copyrightHeader}
            package nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.fieldDefinitions;
            
            import nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.baseTypes.BaseType;
            import nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.FieldDefinition;
            
            ${autoGenerated}
            
            public enum FieldDefinitions {
                ALARM,
                ARRAY,
                BOOLEAN,
                DAY_OF_WEEK,
                FILE_TYPE,
                HR_TIME_IN_ZONE,
                HR_ZONE_HIGH_BOUNDARY,
                TEMPERATURE,
                TIMESTAMP,
                COORDINATE,
            """;

    private static int FILE_WRITTEN_COUNTER = 0;

    public static void main(final String[] args) throws Exception {
        final long startTime = System.currentTimeMillis();

        final String pathToJson = (args.length > 0) ? args[0] : "FitCodeGenerator/src/main/resources/fit_profile.json";
        final String pathToOutput = (args.length > 1) ? args[1] : "app/build/generated/sources/fit/nodomain/freeyourgadget/gadgetbridge/service/devices/garmin/fit/";
        final String pathToManual = (args.length > 2) ? args[2] : "app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/garmin/fit/";

        final File jsonFile = new File(pathToJson).getAbsoluteFile();
        final File outputDir = new File(pathToOutput).getAbsoluteFile();

        final SortedSet<FitMessage> messages = new TreeSet<>();
        final SortedSet<FitEnum> enumerations = new TreeSet<>();
        final SortedSet<FitDevice> devices = new TreeSet<>();
        try (final FileReader reader = new FileReader(jsonFile, StandardCharsets.UTF_8)) {
            readJson(reader, messages, enumerations, devices);
        }

        if (false) {
            // only used for mass updates to fit_profile.json
            //modifyProfile(messages, enumerations);
            try (Writer writer = new FileWriter(jsonFile, StandardCharsets.UTF_8)) {
                writeJSon(writer, messages, enumerations, devices);
            }
        }

        final File messagesTarget = new File(outputDir, "messages").getAbsoluteFile();
        final File messagesManual = new File(pathToManual, "messages").getAbsoluteFile();

        final File enumsTarget = new File(outputDir, "enums").getAbsoluteFile();

        final File fieldTarget = new File(outputDir, "fieldDefinitions").getAbsoluteFile();
        final File fieldManual = new File(pathToManual, "fieldDefinitions").getAbsoluteFile();

        prepareTargetFolder(messagesTarget);
        prepareTargetFolder(enumsTarget);
        prepareTargetFolder(fieldTarget);

        generateNativeFile(messages, outputDir);
        generateFitRecordDataFactory(messages, messagesTarget);
        for (final FitMessage message : messages) {
            generateFitMessageClassFile(message, messagesTarget, messagesManual);
        }
        for (final FitEnum enumeration : enumerations) {
            generateFitEnumFile(enumeration, enumsTarget);
            generateFitEnumFieldDefinitionFile(enumeration, fieldTarget, fieldManual);
        }
        generateFitFieldDefinitionsFile(enumerations, fieldTarget);

        final long time = System.currentTimeMillis() - startTime;
        System.out.println("Written " + FILE_WRITTEN_COUNTER + " files to " + outputDir + " in " + time + "ms");
    }

    private static void generateFitEnumFieldDefinitionFile(final FitEnum enumeration,
                                                           final File fieldTarget,
                                                           final File fieldManual) throws IOException {
        final File manualFile = new File(fieldManual, "FieldDefinition" + enumeration.name + ".java");
        if (manualFile.exists()) {
            // a manualy defined FieldDefinition exists
            return;
        }

        final String output = FIELD_DEFINTION
                .replace("${copyrightHeader}", COPYRIGHT_HEADER)
                .replace("${autoGenerated}", AUTO_GENRATED)
                .replace("${enumType}", enumeration.name);

        final File fieldDefinitionFile = new File(fieldTarget, "FieldDefinition" + enumeration.name + ".java");
        Files.writeString(fieldDefinitionFile.toPath(), output, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
        fileWritten(fieldDefinitionFile);
    }

    private static void fileWritten(final File outputFile) throws IOException {
        if (Boolean.getBoolean("verbose")) {
            System.out.println("Written " + outputFile.getCanonicalPath());
        }
        FILE_WRITTEN_COUNTER++;
    }

    private static void generateFitFieldDefinitionsFile(final Iterable<FitEnum> enumerations,
                                                        final File fieldTarget) throws IOException {
        final StringBuilder builder = new StringBuilder(FIELD_DEFINITIONS
                .replace("${copyrightHeader}", COPYRIGHT_HEADER)
                .replace("${autoGenerated}", AUTO_GENRATED)
        );
        for (final FitEnum fitEnum : enumerations) {
            builder.append("    ");
            builder.append(fitEnum.name);
            builder.append(",\n");
        }
        builder.append("    ;\n");
        builder.append("    public static FieldDefinition create(int localNumber, int size, FieldDefinitions field, BaseType baseType, String name, int scale, int offset) {\n");
        builder.append("        return switch(field) {\n");
        for (final FitEnum fitEnum : enumerations) {
            builder.append(ENUM_CREATION.replace("${enumType}", fitEnum.name));
        }
        builder.append("            default -> throw new UnsupportedOperationException(field.toString());\n");
        builder.append("        };\n");
        builder.append("    }\n");
        builder.append("}\n");

        final File outputFile = new File(fieldTarget, "FieldDefinitions.java");
        Files.writeString(outputFile.toPath(), builder.toString(), StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
        fileWritten(outputFile);
    }

    private static void prepareTargetFolder(final File targetDir) {
        if (targetDir.exists()) {
            for (final File file : targetDir.listFiles()) {
                file.delete();
            }
        } else {
            targetDir.mkdirs();
        }
    }

    private static void generateFitEnumFile(final FitEnum enumeration, final File enumsTarget) throws IOException {
        final File enumFile = new File(enumsTarget, enumeration.name + ".java");
        try (final PrintWriter printer = new PrintWriter(enumFile, StandardCharsets.UTF_8)) {
            printer.println(COPYRIGHT_HEADER);
            printer.println("package nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.enums;");
            printer.println();

            final FitEnumEntry cannary = enumeration.entries.first();

            if (null != cannary.label) {
                // enum with StringRes
                printer.println("import androidx.annotation.StringRes;");
                printer.println();
                printer.println("import nodomain.freeyourgadget.gadgetbridge.R;");
                printer.println();
                printer.println(AUTO_GENRATED);
                printer.format(Locale.ROOT, "public enum %s {", enumeration.name).println();
                for (final FitEnumEntry entry : enumeration.entries) {
                    printer.format(Locale.ROOT, "    %s(%d, %s),",
                            entry.name, entry.num, entry.label);
                    printer.println();
                }
                printer.println("    ;");
                printer.println();
                printer.println("    public final int num;");
                printer.println();
                printer.println("    @StringRes");
                printer.println("    public final int label;");
                printer.println();
                printer.format(Locale.ROOT, "    %s(final int n, @StringRes final int l) {", enumeration.name).println();
                printer.println("        num = n;");
                printer.println("        label = l;");
                printer.println("    }");
                printer.println();
                printer.println("    @Override");
                printer.println("    public String toString() {");
                printer.println("        return EnumHelper.getString(label, this);");
                printer.println("    }");
                printer.println("}");
            } else if (cannary.text != null) {
                // enum with direct text
                printer.println("import androidx.annotation.NonNull;");
                printer.println();
                printer.println(AUTO_GENRATED);
                printer.format(Locale.ROOT, "public enum %s {", enumeration.name).println();
                for (final FitEnumEntry entry : enumeration.entries) {
                    printer.format(Locale.ROOT, "    %s(%d, \"%s\"),",
                            entry.name, entry.num, entry.text);
                    printer.println();
                }
                printer.println("    ;");
                printer.println();
                printer.println("    public final int num;");
                printer.println();
                printer.println("    @NonNull");
                printer.println("    public final String text;");
                printer.println();
                printer.format(Locale.ROOT, "    %s(final int n, @NonNull final String t) {", enumeration.name).println();
                printer.println("        num = n;");
                printer.println("        text = t;");
                printer.println("    }");
                printer.println();
                printer.println("    @Override");
                printer.println("    public String toString() {");
                printer.println("        return text;");
                printer.println("    }");
                printer.println("}");
            } else {
                // plain enum
                printer.println();
                printer.println(AUTO_GENRATED);
                printer.format(Locale.ROOT, "public enum %s {", enumeration.name).println();
                for (final FitEnumEntry entry : enumeration.entries) {
                    printer.format(Locale.ROOT, "    %s(%d),", entry.name, entry.num).println();
                }
                printer.println("    ;");
                printer.println();
                printer.println("    public final int num;");
                printer.println();
                printer.format(Locale.ROOT, "    %s(final int n) {", enumeration.name).println();
                printer.println("        num = n;");
                printer.println("    }");
                printer.println("}");
            }
        }
        fileWritten(enumFile);
    }

    private static void generateNativeFile(final SortedSet<FitMessage> messages, final File outputDir) throws IOException {
        final StringWriter writer = new StringWriter();
        final PrintWriter printer = new PrintWriter(writer);
        generateNativeFile(messages, printer);
        printer.println("}");
        printer.flush();

        final File nativeFile = new File(outputDir, "NativeFITMessages.java");
        Files.writeString(nativeFile.toPath(), writer.toString(), StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
        fileWritten(nativeFile);
    }

    private static void readJson(final Reader reader, final Collection<FitMessage> messages, final Collection<FitEnum> enumerations, SortedSet<FitDevice> devices) {
        final JSONTokener tokenizer = new JSONTokener(reader);
        final JSONObject root = new JSONObject(tokenizer);

        final JSONArray messagesJson = root.getJSONArray("messages");
        for (int messageIndex = 0; messageIndex < messagesJson.length(); messageIndex++) {
            final JSONObject messageJson = messagesJson.getJSONObject(messageIndex);
            final FitMessage messageFit = new FitMessage();
            messageFit.num = messageJson.getInt("num");
            messageFit.name = messageJson.getString("name");
            final JSONArray fieldsJson = messageJson.getJSONArray("fields");
            for (int fieldIndex = 0; fieldIndex < fieldsJson.length(); fieldIndex++) {
                final JSONObject fieldJson = fieldsJson.getJSONObject(fieldIndex);
                final FitField fieldFit = new FitField();
                fieldFit.num = fieldJson.getInt("num");
                fieldFit.name = fieldJson.getString("name");

                fieldFit.type = fieldJson.has("type") ? fieldJson.getString("type") : null;
                fieldFit.scale = fieldJson.has("scale") ? fieldJson.getDouble("scale") : 1.0;
                fieldFit.offset = fieldJson.has("offset") ? fieldJson.getDouble("offset") : 0.0;
                fieldFit.arrayLen = fieldJson.has("arrayLen") ? fieldJson.getInt("arrayLen") : -1;
                fieldFit.stringLen = fieldJson.has("stringLen") ? fieldJson.getInt("stringLen") : -1;
                fieldFit.UOM = fieldJson.has("UOM") ? fieldJson.getString("UOM") : null;
                fieldFit.base = fieldJson.getString("base");
                if (fieldFit.arrayLen < 0) {
                    fieldFit.arrayLen = -1;
                } else {
                    fieldFit.type = "ARRAY";
                }
                if (fieldFit.stringLen <= 0) {
                    fieldFit.stringLen = -1;
                }
                if (fieldFit.base != null && fieldFit.type != null && fieldFit.base.contentEquals(fieldFit.type)) {
                    fieldFit.type = null;
                }
                messageFit.fields.add(fieldFit);
            }
            messages.add(messageFit);
        }

        final JSONArray enumerationsJson = root.getJSONArray("enumerations");
        for (int enumIndex = 0; enumIndex < enumerationsJson.length(); enumIndex++) {
            final JSONObject enumJson = enumerationsJson.getJSONObject(enumIndex);
            final FitEnum enumFit = new FitEnum();
            enumFit.name = enumJson.getString("name");
            final JSONArray entries = enumJson.getJSONArray("entries");
            for (int entryIndex = 0; entryIndex < entries.length(); entryIndex++) {
                final JSONObject entryJson = entries.getJSONObject(entryIndex);
                final FitEnumEntry entryFit = new FitEnumEntry();
                entryFit.num = entryJson.getInt("num");
                entryFit.name = entryJson.getString("name");
                entryFit.label = entryJson.has("label") ? entryJson.getString("label") : null;
                entryFit.text = entryJson.has("text") ? entryJson.getString("text") : null;
                enumFit.entries.add(entryFit);
            }
            enumerations.add(enumFit);
        }

        final JSONArray devicesJson = root.getJSONArray("devices");
        for (int deviceIndex = 0; deviceIndex < devicesJson.length(); deviceIndex++) {
            final JSONObject deviceJson = devicesJson.getJSONObject(deviceIndex);
            final FitDevice device = new FitDevice(
                    deviceJson.getInt("manufacturer"),
                    deviceJson.getInt("product"),
                    deviceJson.getString("name")
            );
            devices.add(device);
        }
    }

    private static void generateNativeFile(final SortedSet<FitMessage> fitMessages, final PrintWriter printer) {
        printer.println(COPYRIGHT_HEADER);
        printer.println(NATIVE_HEADER);

        for (final FitMessage messsage : fitMessages) {
            boolean directAccess = Arrays.binarySearch(DIRECT_ACCESS_MESSAGES, messsage.num) >= 0;
            if (directAccess) {
                printer.println("\tpublic static NativeFITMessage FIT_" + messsage.name + " = new NativeFITMessage(" + messsage.num + ", \"" + messsage.name + "\", List.of(");
            } else {
                printer.println("\tpublic static NativeFITMessage FIT_" + messsage.name + "() { return new NativeFITMessage(" + messsage.num + ", \"" + messsage.name + "\", List.of(");
            }

            final FitField[] fields = messsage.fields.toArray(new FitField[0]);
            for (int i = 0; i < fields.length; i++) {
                final FitField field = fields[i];
                // TODO: offset - add support for non-int in Java stage
                // TODO: scale - add support for non-int in Java stage
                // TODO: support - add support for string arrays in Java stage
                int size = field.stringLen > 0 ? field.stringLen : (field.arrayLen >= 0 ? field.arrayLen : 0);
                final Number scale;
                {
                    final long longScale = Math.round(field.scale);
                    if (longScale == field.scale) {
                        scale = longScale;
                    } else {
                        scale = field.scale;
                    }
                }
                final Number offset;
                {
                    final long longOffset = Math.round(field.offset);
                    if (longOffset == field.offset) {
                        offset = longOffset;
                    } else {
                        offset = field.offset;
                    }
                }

                if (size > 0) {
                    printer.print("\t\t\tnew FieldDefinitionPrimitive(" +
                            field.num + ", "
                            + field.base + ", "
                            + size + ", \""
                            + field.name + "\", "
                            + (field.type == null ? "null" : field.type) + ", "
                            + scale + ", "
                            + offset + ")"
                    );
                } else if (field.offset != 0 || field.scale != 1 || field.type != null || field.UOM != null) {
                    printer.print("\t\t\tnew FieldDefinitionPrimitive(" +
                            field.num + ", "
                            + field.base + ", \""
                            + field.name + "\", "
                            + (field.type == null ? "null" : field.type) + ", "
                            + scale + ", "
                            + offset + ")"
                    );
                } else {
                    printer.print("\t\t\tnew FieldDefinitionPrimitive(" +
                            field.num + ", " + field.base + ", \"" + field.name + "\")");
                }

                final boolean isLast = i + 1 >= fields.length;
                if (!isLast) {
                    printer.print(",");
                }

                if (null != field.UOM) {
                    printer.print(" // UNIT_");
                    printer.print(field.UOM);
                }

                printer.println();
            }
            if (directAccess) {
                printer.println("\t));");
            } else {
                printer.println("\t));}");
            }
        }

        printer.println("\tstatic final SortedMap<Integer, NativeFITMessage> mapKnownMessages() {");
        printer.println("\t\tSortedMap<Integer, NativeFITMessage> map = new TreeMap<>();");
        printer.println("\t\tNativeFITMessage mesg;");
        for (final FitMessage message : fitMessages) {
            boolean directAccess = Arrays.binarySearch(DIRECT_ACCESS_MESSAGES, message.num) >= 0;
            if (directAccess) {
                printer.println("\t\tmap.put(" + message.num + ", FIT_" + message.name + ");");
            } else {
                printer.println("\t\tmap.put(" + message.num + ", FIT_" + message.name + "());");
            }
        }
        printer.println("\t\treturn map;");
        printer.println("\t}");
    }

    private static void generateFitRecordDataFactory(final SortedSet<FitMessage> messages, final File outputDir) throws IOException {
        final List<String> switchCases = new ArrayList<>();

        for (final FitMessage value : messages) {
            final String className = "Fit" + capitalize(toCamelCase(value.name));
            switchCases.add("            case %d -> new %s(recordDefinition, recordHeader);".formatted(value.num, className));
        }

        final String template = """
                ${copyrightHeader}
                package nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.messages;
                
                import nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.RecordData;
                import nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.RecordDefinition;
                import nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.RecordHeader;
                
                ${autoGenerated}
                public class FitRecordDataFactory {
                    private FitRecordDataFactory() {
                        // use create
                    }
                
                    public static RecordData create(final RecordDefinition recordDefinition, final RecordHeader recordHeader) {
                        return switch (recordDefinition.getNativeFITMessage().getNumber()) {
                ${switchCases}
                             default -> new RecordData(recordDefinition, recordHeader);
                        };
                    }
                }
                """;

        final String result = template
                .replace("${copyrightHeader}", COPYRIGHT_HEADER.strip())
                .replace("${autoGenerated}", AUTO_GENRATED)
                .replace("${switchCases}", String.join("\n", switchCases))
                .replaceAll("\\R", System.lineSeparator());

        final File outputFile = new File(outputDir, "FitRecordDataFactory.java");
        Files.writeString(outputFile.toPath(), result, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
        fileWritten(outputFile);
    }

    private static void generateFitMessageClassFile(final FitMessage nativeFITMessage, final File messagesDir, final File manualMessageDir) throws IOException {
        String className = "Fit" + capitalize(toCamelCase(nativeFITMessage.name));
        if (new File(manualMessageDir, className + ".java").exists()) {
            className = "Abstract" + className;
        }
        final File outputFile = new File(
                messagesDir,
                className + ".java"
        );

        //
        // Collect all imports
        //
        final List<String> imports = new ArrayList<>(List.of(
                "androidx.annotation.Nullable",
                "nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.FitRecordDataBuilder",
                "nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.RecordData",
                "nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.RecordDefinition",
                "nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.RecordHeader"
        ));
        imports.addAll(getImports(outputFile));

        //
        // Add field-specific imports
        //
        for (final FitField primitive : nativeFITMessage.getFieldDefinitionPrimitives()) {
            final FieldClass fieldType = getFieldType(primitive);
            if (!Objects.requireNonNull(fieldType.getCanonicalName()).startsWith("java.lang")) {
                if (fieldType.isArray()) {
                    imports.add(fieldType.getCanonicalName().replace("[]", ""));
                } else {
                    imports.add(fieldType.getCanonicalName());
                }
            }
        }

        //
        // Deduplicate + sort imports
        //
        final Set<String> uniqueImports = new TreeSet<>(imports);

        //
        // Copyright header + package
        //
        final StringBuilder sb = new StringBuilder();
        sb.append(COPYRIGHT_HEADER.strip()).append("\n");
        sb.append("package nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.messages;\n\n");

        //
        // Imports, grouped by prefix
        //
        final List<String> importOrder = List.of("androidx", "java.", "nodomain.freeyourgadget");
        for (final String prefix : importOrder) {
            boolean wroteAny = false;
            for (final String i : uniqueImports) {
                if (i.startsWith(prefix)) {
                    sb.append("import ").append(i).append(";\n");
                    wroteAny = true;
                }
            }
            if (wroteAny) {
                sb.append("\n"); // only add blank line if group was non-empty
            }
        }

        //
        // Imports - rest
        //
        boolean wroteOthers = false;
        for (final String i : uniqueImports) {
            if (importOrder.stream().noneMatch(i::startsWith)) {
                sb.append("import ").append(i).append(";\n");
                wroteOthers = true;
            }
        }
        if (wroteOthers) {
            sb.append("\n");
        }

        //
        // Class javadoc + constructor
        //
        sb.append("""
                ${autoGenerated}
                public class ${className} extends RecordData {
                    public ${className}(final RecordDefinition recordDefinition, final RecordHeader recordHeader) {
                        super(recordDefinition, recordHeader);
                
                        final int nativeNumber = recordDefinition.getNativeFITMessage().getNumber();
                        if (nativeNumber != ${nativeNumber}) {
                            throw new IllegalArgumentException("${className} expects native messages of " + ${nativeNumber} + ", got " + nativeNumber);
                        }
                    }
                """
                .replace("${autoGenerated}", AUTO_GENRATED)
                .replace("${className}", className)
                .replace("${nativeNumber}", String.valueOf(nativeFITMessage.num))
        );

        //
        // Field accessors
        //
        for (final FitField primitive : nativeFITMessage.getFieldDefinitionPrimitives()) {
            final FieldClass fieldType = getFieldType(primitive);
            final String fieldTypeName;
            final String accessorTemplate;
            if (fieldType.isArray()) {
                fieldTypeName = fieldType.getSimpleName().replace("[]", "");
                accessorTemplate = """
                        
                            @Nullable
                            public ${fieldType}[] ${getterName}() {
                                return getArrayFieldByNumber(${primitiveNumber}, ${fieldType}.class);
                            }
                        """;
            } else {
                fieldTypeName = fieldType.getSimpleName();
                accessorTemplate = """
                        
                            @Nullable
                            public ${fieldType} ${getterName}() {
                                return getFieldByNumber(${primitiveNumber}, ${fieldType}.class);
                            }
                        """;
            }

            if (primitive.UOM != null) {
                sb.append("    /// UNIT_" + primitive.UOM);
            }
            sb.append(
                    accessorTemplate
                            .replace("${fieldType}", fieldTypeName)
                            .replace("${getterName}", method("get", primitive))
                            .replace("${primitiveNumber}", String.valueOf(primitive.getNumber()))
            );
        }

        //
        // Builder
        //
        sb.append("""
                
                    /**
                     * @noinspection unused
                     */
                    public static class Builder extends FitRecordDataBuilder {
                        public Builder() {
                            super(${nativeNumber});
                        }
                """
                .replace("${nativeNumber}", String.valueOf(nativeFITMessage.num))
        );

        for (final FitField primitive : nativeFITMessage.getFieldDefinitionPrimitives()) {
            final FieldClass fieldType = getFieldType(primitive);
            final String fieldTypeName = fieldType.getSimpleName();

            if (primitive.UOM != null) {
                sb.append("        /// UNIT_" + primitive.UOM);
            }
            sb.append("""
                    
                            public Builder ${setterName}(final ${fieldType} value) {
                                setFieldByNumber(${primitiveNumber}, ${castIfArray}value);
                                return this;
                            }
                    """
                    .replace("${setterName}", method("set", primitive))
                    .replace("${fieldType}", fieldTypeName)
                    .replace("${primitiveNumber}", String.valueOf(primitive.getNumber()))
                    .replace("${castIfArray}", fieldType.isArray() ? "(Object[]) " : "")
            );
        }

        sb.append("""
                
                        @Override
                        public ${className} build() {
                            return (${className}) super.build();
                        }
                
                        @Override
                        public ${className} build(final int localMessageType) {
                            return (${className}) super.build(localMessageType);
                        }
                    }
                """
                .replace("${className}", className)
        );
        sb.append("}\n");

        final String output = sb.toString().replaceAll("\\R", System.lineSeparator());

        Files.writeString(outputFile.toPath(), output, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
        fileWritten(outputFile);
    }

    private static FieldClass getFieldType(final FitField primitive) {
        if (primitive.getType() != null) {
            return switch (primitive.getType()) {
                case "ALARM" -> new FieldClass(LocalTime.class);
                case "ARRAY" ->
                        primitive.getBase().contentEquals("STRING") ? new FieldClass(String[].class) : new FieldClass(Number[].class);
                case "BOOLEAN" -> new FieldClass(Boolean.class);
                case "DAY_OF_WEEK" -> new FieldClass(DayOfWeek.class);
                case "ExerciseCategory" ->
                        new FieldClass("nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.enums.ExerciseCategory[]", true);
                case "FILE_TYPE" ->
                        new FieldClass("nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.FileType.FILETYPE");
                case "HR_TIME_IN_ZONE" -> new FieldClass(Double[].class);
                case "HR_ZONE_HIGH_BOUNDARY" -> new FieldClass(Integer[].class);
                case "TEMPERATURE" -> new FieldClass(Integer.class);
                case "TIMESTAMP" -> new FieldClass(Long.class);
                case "COORDINATE" -> new FieldClass(Double.class);
                default ->
                        new FieldClass("nodomain.freeyourgadget.gadgetbridge.service.devices.garmin.fit.enums."
                                + primitive.getType());
            };
        }

        switch (primitive.getBase()) {
            case "ENUM":
            case "SINT8":
            case "UINT8":
            case "SINT16":
            case "UINT16":
            case "UINT8Z":
            case "UINT16Z":
            case "BYTE":
                if (primitive.getScale() != 1) {
                    return new FieldClass(Float.class);
                } else {
                    return new FieldClass(Integer.class);
                }
            case "SINT32":
            case "UINT32":
            case "UINT32Z":
            case "SINT64":
            case "UINT64":
            case "UINT64Z":
                if (primitive.getScale() != 1) {
                    return new FieldClass(Double.class);
                } else {
                    return new FieldClass(Long.class);
                }
            case "STRING":
                return new FieldClass(String.class);
            case "FLOAT32":
                return new FieldClass(Float.class);
            case "FLOAT64":
                return new FieldClass(Double.class);
        }

        throw new RuntimeException("Unknown base type " + primitive.getBase());
    }

    private static String toCamelCase(final String str) {
        final StringBuilder sb = new StringBuilder(str.toLowerCase(Locale.ROOT));

        for (int i = 0; i < sb.length(); i++) {
            if (sb.charAt(i) == '_') {
                sb.deleteCharAt(i);
                sb.replace(i, i + 1, String.valueOf(Character.toUpperCase(sb.charAt(i))));
            }
        }

        return sb.toString();
    }

    private static String method(final String methodName, final FitField primitive) {
        return methodName + capitalize(toCamelCase(primitive.getName()));
    }

    private static String capitalize(final String str) {
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }

    /**
     * Get all the imports from an existing java file.
     */
    private static List<String> getImports(final File file) throws IOException {
        if (file.exists()) {
            final String fileContents = Files.readString(file.toPath(), StandardCharsets.UTF_8);
            final List<String> imports = new ArrayList<>();

            final Matcher m = Pattern.compile("import (.+);")
                    .matcher(fileContents);
            while (m.find()) {
                imports.add(m.group(1));
            }
            return imports;
        }

        return Collections.emptyList();
    }

    private static void modifyProfile(final SortedSet<FitMessage> messages, final SortedSet<FitEnum> enumerations) throws Exception {
        /*for (final FitMessage message : messages) {
            for (final FitField field : message.fields) {
                if ("TIMESTAMP".equals(field.type)) {
                    field.UOM = "UNIT_SECONDS";
                } else if (field.num == 253 && field.name == "timestamp") {
                    field.type = "TIMESTAMP";
                    field.UOM = "UNIT_SECONDS";
                }
            }
        }*/
    }

    private static void writeJSon(final Writer writer, final SortedSet<FitMessage> messages,
                                  final SortedSet<FitEnum> enums, final SortedSet<FitDevice> devices) throws IOException {
        try (JsonWriter o = new JsonWriter(writer)) {
            o.setSerializeNulls(true);
            o.setIndent("  ");
            o.beginObject();

            o.name("messages");
            o.beginArray();
            for (final FitMessage m : messages) {
                o.beginObject();
                o.name("num").value(m.num);
                o.name("name").value(m.name);
                o.name("fields");
                o.beginArray();
                for (final FitField field : m.getFieldDefinitionPrimitives()) {
                    printJSon(field, o);
                }
                o.endArray();
                o.endObject();
            }
            o.endArray();

            o.name("enumerations");
            o.beginArray();
            for (final FitEnum fitEnum : enums) {
                o.beginObject();
                o.name("name").value(fitEnum.name);
                o.name("entries");
                o.beginArray();
                for (final FitEnumEntry fitEnumEntry : fitEnum.entries) {
                    o.beginObject();
                    o.setFormattingStyle(FormattingStyle.COMPACT);
                    o.name("num").value(fitEnumEntry.num);
                    o.name("name").value(fitEnumEntry.name);
                    if (fitEnumEntry.label != null) {
                        o.name("label").value(fitEnumEntry.label);
                    }
                    if (fitEnumEntry.text != null) {
                        o.name("text").value(fitEnumEntry.text);
                    }
                    o.endObject();
                    o.setFormattingStyle(FormattingStyle.PRETTY);
                }
                o.endArray();
                o.endObject();
            }
            o.endArray();

            o.name("devices");
            o.beginArray();
            for (final FitDevice fitDevice : devices) {
                o.beginObject();
                o.setFormattingStyle(FormattingStyle.COMPACT);
                o.name("manufacturer").value(fitDevice.manufacturer);
                o.name("product").value(fitDevice.product);
                o.name("name").value(fitDevice.name);
                o.endObject();
                o.setFormattingStyle(FormattingStyle.PRETTY);
            }
            o.endArray();

            o.endObject();
        }
    }

    private static void printJSon(final FitField f, final JsonWriter o) throws IOException {
        o.beginObject();
        o.setFormattingStyle(FormattingStyle.COMPACT);
        o.name("num").value(f.num);
        o.name("name").value(f.name);
        o.name("base").value(f.base);
        if (1 != f.scale) {
            o.name("scale");
            long l = Math.round(f.scale);
            if (l == f.scale) {
                o.value(l);
            } else {
                o.value(f.scale);
            }
        }
        if (f.type != null && !"ARRAY".contentEquals(f.type)) {
            o.name("type").value(f.type);
        }
        if (0 != f.offset) {
            o.name("offset");
            long l = Math.round(f.offset);
            if (l == f.offset) {
                o.value(l);
            } else {
                o.value(f.offset);
            }
        }
        if (f.arrayLen >= 0) {
            o.name("arrayLen").value(f.arrayLen);
        }
        if (f.stringLen >= 0) {
            o.name("stringLen").value(f.stringLen);
        }
        if (f.UOM != null) {
            o.name("UOM").value(f.UOM);
        }
        o.endObject();
        o.setFormattingStyle(FormattingStyle.PRETTY);
    }

    static class FitField implements Comparable<FitField> {
        int num;
        String name;
        String type;
        String base;
        double scale;
        double offset;
        int arrayLen;
        int stringLen;
        String UOM;

        FitField() {
            scale = 1;
            offset = 0;
            arrayLen = -1;
            stringLen = -1;
        }

        @Override
        public int compareTo(final FitField o) {
            return Integer.compare(num, o.num);
        }

        String getName() {
            return name;
        }

        String getType() {
            return type;
        }

        String getBase() {
            return base;
        }

        int getNumber() {
            return num;
        }

        double getScale() {
            return scale;
        }
    }

    static final class FitEnum implements Comparable<FitEnum> {
        String name;
        SortedSet<FitEnumEntry> entries;

        FitEnum() {
            name = null;
            entries = new TreeSet<>();
        }

        @Override
        public int compareTo(final FitEnum o) {
            return name.compareTo(o.name);
        }
    }

    static final class FitEnumEntry implements Comparable<FitEnumEntry> {
        int num;
        String name;
        String text;
        String label;

        FitEnumEntry() {
            num = -1;
            name = null;
            text = null;
            label = null;
        }

        @Override
        public int compareTo(final FitEnumEntry o) {
            return Integer.compare(num, o.num);
        }
    }

    static final class FitMessage implements Comparable<FitMessage> {
        int num;
        String name;
        SortedSet<FitField> fields;

        FitMessage() {
            num = -1;
            name = null;
            fields = new TreeSet<>();
        }

        @Override
        public int compareTo(final FitMessage o) {
            return Integer.compare(num, o.num);
        }

        Set<FitField> getFieldDefinitionPrimitives() {
            return fields;
        }
    }

    record FieldClass(String CanonicalName, boolean isArray) {
        FieldClass(final String canonicalName) {
            this(canonicalName, false);
        }

        FieldClass(final Class<?> clazz) {
            this(clazz.getCanonicalName(), clazz.isArray());
        }

        String getCanonicalName() {
            return CanonicalName;
        }

        String getSimpleName() {
            int index = CanonicalName.lastIndexOf('.');
            return CanonicalName.substring(index + 1);
        }
    }

    record FitDevice(int manufacturer, int product, String name) implements Comparable<FitDevice> {
        @Override
        public int compareTo(FitDevice o) {
            int cmp = Integer.compare(manufacturer, o.manufacturer);
            if (cmp != 0) {
                return cmp;
            }
            cmp = Integer.compare(product, o.product);
            if (cmp != 0) {
                return cmp;
            }
            return name.compareTo(o.name);
        }
    }
}