steps:
  tests:
    image: codeberg.org/freeyourgadget/android-fdroid-tools:37.0.0-0
    environment:
      # Explicitly enable filesystem watch, reduces build time by 1m30s
      # https://stackoverflow.com/questions/71559269/why-does-gradle-initializing-sometimes-take-very-long
      GRADLE_OPTS: "-Dorg.gradle.vfs.watch=true -XX:TieredStopAtLevel=1"
    commands:
      - pwd #bump
      # https://github.com/robolectric/robolectric/issues/3202
      - ./gradlew :app:testBangleDebugUnitTest :app:testMainDebugUnitTest

#when:
#repo: Freeyourgadget/Gadgetbridge
#branch: master
#this doesn't work yet:
#https://github.com/woodpecker-ci/woodpecker/issues/687

when:
  # Everything except cron (nightly) and deployment
  - event: push
  - event: pull_request
  - event: tag
  - event: manual
